# Generated by Django 3.1.12 on 2021-12-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0008_auto_20211221_1901"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="meta",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The meta field is used to maintain meta data for survey",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="surveyanswer",
            name="meta",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The meta field is used to maintain meta data for survey answers",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="surveychoice",
            name="meta",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The meta field is used to maintain meta data for survey choice",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="meta",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The meta field is used to maintain meta data for survey question",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="meta",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The meta field is used to maintain meta data for survey response",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="surveysection",
            name="meta",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The meta field is used to maintain meta data for survey sections. ",
                null=True,
            ),
        ),
    ]
