
from abc import ABC

class Industrysoftwareitesbrainstation23TalentyourservicePageLocators(ABC):

    skiptocontent_title: str = "Skip to content"
    mainmenu_type: str = "button"
    home_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[1]/a"
    services_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[2]/a"
    adobeexperiencemanager_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[2]/ul/li[1]/a"
    bankingsolution_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[2]/ul/li[2]/a"
    mobileappdevelopment_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[2]/ul/li[3]/a"
    arvrsolution_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[2]/ul/li[4]/a"
    augmentedreality_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[2]/ul/li[4]/ul/li[1]/a"
    virtualreality_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[2]/ul/li[4]/ul/li[2]/a"
    3dmodeling_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[2]/ul/li[4]/ul/li[3]/a"
    gamestudio_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[2]/ul/li[5]/a"
    cloudandcybersecurity_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[2]/ul/li[6]/a"
    erp_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[2]/ul/li[7]/a"
    ecommercesolution_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[2]/ul/li[8]/a"
    sharepointservices_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[2]/ul/li[9]/a"
    businessintelligence_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[2]/ul/li[10]/a"
    softwaretestingasservice_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[2]/ul/li[12]/a"
    industries_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[3]/a"
    fintech_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[3]/ul/li[1]/a"
    healthcare_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[3]/ul/li[2]/a"
    telecom_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[3]/ul/li[3]/a"
    realestate_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[3]/ul/li[4]/a"
    softwareites_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[3]/ul/li[5]/a"
    ecommerce_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[3]/ul/li[6]/a"
    education_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[3]/ul/li[7]/a"
    retail_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[3]/ul/li[8]/a"
    automotive_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[3]/ul/li[9]/a"
    startup_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[3]/ul/li[10]/a"
    casestudies_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[4]/a"
    about_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[5]/a"
    aboutus_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[5]/ul/li[1]/a"
    ourpartners_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[5]/ul/li[2]/a"
    media_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[5]/ul/li[3]/a"
    career_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[5]/ul/li[4]/a"
    blog_xpath: str = "//body/div[1]/header/div/div/div/div/div[3]/div/nav/div/ul/li[6]/a"
    cookiesettings_xpath: str = "//body/div[2]/span/a[1]"
    accept_id: str = "cookie_action_close_header"
    close_id: str = "cliModalClose"
    saveaccept_id: str = "wt-cli-privacy-save-btn"

    PAGE_LOCATOR_TESTER = "Page locator found."
    '''This constsant is for connectivity test only  [BS23]'''