
from abc import ABC

class PricingforcypresstestingframeworkcypressiotestingtoolsPageLocators(ABC):

    closemenu_id: str = "react-burger-cross-btn"
    _name: str = "hutk"
    contactus_type: str = "button"
    previous_type: str = "button"
    zocdoc_title: str = "Zocdoc"
    vidyard_title: str = "Vidyard"
    johnson___johnson_title: str = "Johnson & Johnson"
    condé_nast_title: str = "Condé Nast"
    trulia_title: str = "Trulia"
    paypal_title: str = "PayPal"
    walt_disney_studios_title: str = "Walt Disney Studios"
    dhl_title: str = "DHL"
    hashicorp_title: str = "Hashicorp"
    airtable__title: str = "Airtable "
    room___board_title: str = "Room & Board"
    pendo_title: str = "Pendo"
    kiwi_title: str = "Kiwi"
    pandora_title: str = "Pandora"
    nielsen_title: str = "Nielsen"
    opentable_title: str = "OpenTable"
    autodesk_title: str = "Autodesk"
    snyk_title: str = "Snyk"
    warby_parker_title: str = "Warby Parker"
    twilio_title: str = "Twilio"
    next_type: str = "button"
    x_id: str = "modal__close"
    your_email_address_id: str = "input-footer-email"
    subscribe_type: str = "submit"
    subscribe_name: str = "form-name"
    5511862_name: str = "portalId"
    345a365f_b011_4b67_b50f_a40a5f4f1b12_name: str = "formId"
    pricing_for_cypress_testing_framework___cypress_io_testing_tools_name: str = "pageName"
    github_title: str = "github"
    twitter_title: str = "twitter"
    facebook_title: str = "facebook"
    mail_us__title: str = "mail us!"
    search____id: str = "vendor-search-handler"
    filterbutton_id: str = "filter-btn-handler"
    select_all_id: str = "select-all-hosts-groups-handler"
    clearfliters_id: str = "clear-filters-handler"
    information_storage_and_access_id: str = "storage-access-group"
    apply_id: str = "filter-apply-handler"
    allowall_id: str = "accept-recommended-btn-handler"

    PAGE_LOCATOR_TESTER = "Page locator found."
    '''This constsant is for connectivity test only  [BS23]'''