# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oneflow/core/job/inter_user_job_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='oneflow/core/job/inter_user_job_info.proto',
  package='oneflow',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n*oneflow/core/job/inter_user_job_info.proto\x12\x07oneflow\"\xdd\x03\n\x10InterUserJobInfo\x12g\n\"input_or_var_op_name2push_job_name\x18\x01 \x03(\x0b\x32;.oneflow.InterUserJobInfo.InputOrVarOpName2pushJobNameEntry\x12i\n#output_or_var_op_name2pull_job_name\x18\x02 \x03(\x0b\x32<.oneflow.InterUserJobInfo.OutputOrVarOpName2pullJobNameEntry\x12\"\n\x1aglobal_model_init_job_name\x18\x04 \x01(\t\x12\"\n\x1aglobal_model_load_job_name\x18\x05 \x01(\t\x12\"\n\x1aglobal_model_save_job_name\x18\x06 \x01(\t\x1a\x43\n!InputOrVarOpName2pushJobNameEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x44\n\"OutputOrVarOpName2pullJobNameEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01')
)




_INTERUSERJOBINFO_INPUTORVAROPNAME2PUSHJOBNAMEENTRY = _descriptor.Descriptor(
  name='InputOrVarOpName2pushJobNameEntry',
  full_name='oneflow.InterUserJobInfo.InputOrVarOpName2pushJobNameEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='oneflow.InterUserJobInfo.InputOrVarOpName2pushJobNameEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='oneflow.InterUserJobInfo.InputOrVarOpName2pushJobNameEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=396,
  serialized_end=463,
)

_INTERUSERJOBINFO_OUTPUTORVAROPNAME2PULLJOBNAMEENTRY = _descriptor.Descriptor(
  name='OutputOrVarOpName2pullJobNameEntry',
  full_name='oneflow.InterUserJobInfo.OutputOrVarOpName2pullJobNameEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='oneflow.InterUserJobInfo.OutputOrVarOpName2pullJobNameEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='oneflow.InterUserJobInfo.OutputOrVarOpName2pullJobNameEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=465,
  serialized_end=533,
)

_INTERUSERJOBINFO = _descriptor.Descriptor(
  name='InterUserJobInfo',
  full_name='oneflow.InterUserJobInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_or_var_op_name2push_job_name', full_name='oneflow.InterUserJobInfo.input_or_var_op_name2push_job_name', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_or_var_op_name2pull_job_name', full_name='oneflow.InterUserJobInfo.output_or_var_op_name2pull_job_name', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='global_model_init_job_name', full_name='oneflow.InterUserJobInfo.global_model_init_job_name', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='global_model_load_job_name', full_name='oneflow.InterUserJobInfo.global_model_load_job_name', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='global_model_save_job_name', full_name='oneflow.InterUserJobInfo.global_model_save_job_name', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_INTERUSERJOBINFO_INPUTORVAROPNAME2PUSHJOBNAMEENTRY, _INTERUSERJOBINFO_OUTPUTORVAROPNAME2PULLJOBNAMEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=533,
)

_INTERUSERJOBINFO_INPUTORVAROPNAME2PUSHJOBNAMEENTRY.containing_type = _INTERUSERJOBINFO
_INTERUSERJOBINFO_OUTPUTORVAROPNAME2PULLJOBNAMEENTRY.containing_type = _INTERUSERJOBINFO
_INTERUSERJOBINFO.fields_by_name['input_or_var_op_name2push_job_name'].message_type = _INTERUSERJOBINFO_INPUTORVAROPNAME2PUSHJOBNAMEENTRY
_INTERUSERJOBINFO.fields_by_name['output_or_var_op_name2pull_job_name'].message_type = _INTERUSERJOBINFO_OUTPUTORVAROPNAME2PULLJOBNAMEENTRY
DESCRIPTOR.message_types_by_name['InterUserJobInfo'] = _INTERUSERJOBINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InterUserJobInfo = _reflection.GeneratedProtocolMessageType('InterUserJobInfo', (_message.Message,), {

  'InputOrVarOpName2pushJobNameEntry' : _reflection.GeneratedProtocolMessageType('InputOrVarOpName2pushJobNameEntry', (_message.Message,), {
    'DESCRIPTOR' : _INTERUSERJOBINFO_INPUTORVAROPNAME2PUSHJOBNAMEENTRY,
    '__module__' : 'oneflow.core.job.inter_user_job_info_pb2'
    # @@protoc_insertion_point(class_scope:oneflow.InterUserJobInfo.InputOrVarOpName2pushJobNameEntry)
    })
  ,

  'OutputOrVarOpName2pullJobNameEntry' : _reflection.GeneratedProtocolMessageType('OutputOrVarOpName2pullJobNameEntry', (_message.Message,), {
    'DESCRIPTOR' : _INTERUSERJOBINFO_OUTPUTORVAROPNAME2PULLJOBNAMEENTRY,
    '__module__' : 'oneflow.core.job.inter_user_job_info_pb2'
    # @@protoc_insertion_point(class_scope:oneflow.InterUserJobInfo.OutputOrVarOpName2pullJobNameEntry)
    })
  ,
  'DESCRIPTOR' : _INTERUSERJOBINFO,
  '__module__' : 'oneflow.core.job.inter_user_job_info_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.InterUserJobInfo)
  })
_sym_db.RegisterMessage(InterUserJobInfo)
_sym_db.RegisterMessage(InterUserJobInfo.InputOrVarOpName2pushJobNameEntry)
_sym_db.RegisterMessage(InterUserJobInfo.OutputOrVarOpName2pullJobNameEntry)


_INTERUSERJOBINFO_INPUTORVAROPNAME2PUSHJOBNAMEENTRY._options = None
_INTERUSERJOBINFO_OUTPUTORVAROPNAME2PULLJOBNAMEENTRY._options = None
# @@protoc_insertion_point(module_scope)
