VERSION_YEAR = 2023
VERSION_MONTH = int('01')
VERSION_DAY = int('09')
VERSION_HOUR = int('07')
VERSION_MINUTE = int('24')
MAJOR_VERSION = 0
MINOR_VERSION = 12
PATCH_VERSION = 202301090724
version_date = '2023/01/09 07:24'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
