"""
Web transactions constants
"""


class Const(object):
    """
    Constant definition for webtxn
    """
    NSKP_SUBSCRIPTION_PATH = "SUBSCRIPTION_PATH"
    NSKP_SUBSCRIPTION_KEY = "SUBSCRIPTION_KEY"
    NSKP_CLOUD_REGION = "CLOUD_REGION"
    NSKP_ZONE_ID = "ZONE_ID"
    NSKP_PROJECT_NUMBER = "PROJECT_NUMBER"
    NSKP_SUBSCRIPTION_ID = "SUBSCRIPTION_ID"
    NSKP_REGIONAL = "REGIONAL"
    NSKP_TIMEOUT = "TIMEOUT"
    NSKP_THREAD_COUNT = "THREAD_COUNT"
    NSKP_OUTSTANDING_MESSAGES = "OUTSTANDING_MESSAGES"
    NSKP_OUTSTANDING_BYTES = "OUTSTANDING_BYTES"
    NKSP_DECOMPRESS_DATA = "DECOMPRESS_DATA"
    NSKP_DEFAULT_TIMEOUT = 180
    NSKP_MIN_THREAD_COUNT = 2
    NSKP_MIN_OUT_MESSAGES = 1000
    NSKP_MIN_OUT_BYTES = 3.5 * 1024 * 1024
    NSKP_DEFAULT_REGIONAL = False
    NKSP_DEFAULT_DECOMPRESS_DATA = False
