
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-09T15:37:37+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "021dde165bb1df1bdcbd055a9fa21bc64c01380e",
 "version": "1.17.1.post0.dev1000"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
