# Generated by Django 3.1.12 on 2021-12-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0003_auto_20211206_0600"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
