# Generated by Django 3.1.12 on 2021-12-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0004_survey_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
