# Generated by Django 3.1.12 on 2021-12-22 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0010_remove_survey_section"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="surveyanswer",
            name="survey_surveyanswer_survey_answers_unique",
        ),
    ]
