# Generated by Django 3.1.12 on 2021-12-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0011_auto_20211222_1418"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveychoice",
            name="question",
        ),
        migrations.RemoveField(
            model_name="surveyquestion",
            name="survey",
        ),
        migrations.AddField(
            model_name="surveychoice",
            name="questions",
            field=models.ManyToManyField(
                blank=True, related_name="choices", to="survey.SurveyQuestion"
            ),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="surveys",
            field=models.ManyToManyField(
                blank=True, related_name="questions", to="survey.Survey"
            ),
        ),
    ]
