# Generated by Django 3.1.12 on 2021-12-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0012_auto_20211223_1935"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
