# Generated by Django 3.1.14 on 2022-04-12 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("survey", "0014_auto_20220315_1650_squashed_0017_auto_20220412_0417"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SurveySection",
            new_name="Section",
        ),
        migrations.RenameModel(
            old_name="SurveyQuestion",
            new_name="Question",
        ),
        migrations.RenameModel(
            old_name="SurveyAnswer",
            new_name="Answer",
        ),
        migrations.RenameModel(
            old_name="SurveyChoice",
            new_name="Choice",
        ),
        migrations.RenameModel(
            old_name="SurveyResponse",
            new_name="Response",
        ),
        migrations.AlterField(
            model_name="question",
            name="choices",
            field=models.ManyToManyField(
                blank=True,
                related_name="questions",
                through="survey.QuestionChoiceMembership",
                to="survey.Choice",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="survey.section",
            ),
        ),
        migrations.AlterField(
            model_name="questionchoicemembership",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices_membership",
                to="survey.question",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="survey.question",
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="questions",
            field=models.ManyToManyField(
                blank=True,
                related_name="surveys",
                through="survey.SurveyQuestionMembership",
                to="survey.Question",
            ),
        ),
        migrations.AlterField(
            model_name="surveyquestionmembership",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surveys_membership",
                to="survey.question",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="meta",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The meta field is used to maintain meta data for questions",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="meta",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The meta field is used to maintain meta data for sections. ",
                null=True,
            ),
        ),
    ]
