# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oneflow/core/job/module_conf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='oneflow/core/job/module_conf.proto',
  package='oneflow',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\"oneflow/core/job/module_conf.proto\x12\x07oneflow\"\'\n\nModuleConf\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0b\n\x03ops\x18\x02 \x03(\t')
)




_MODULECONF = _descriptor.Descriptor(
  name='ModuleConf',
  full_name='oneflow.ModuleConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='oneflow.ModuleConf.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ops', full_name='oneflow.ModuleConf.ops', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['ModuleConf'] = _MODULECONF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModuleConf = _reflection.GeneratedProtocolMessageType('ModuleConf', (_message.Message,), {
  'DESCRIPTOR' : _MODULECONF,
  '__module__' : 'oneflow.core.job.module_conf_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.ModuleConf)
  })
_sym_db.RegisterMessage(ModuleConf)


# @@protoc_insertion_point(module_scope)
