# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oneflow/core/job/scope.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oneflow.core.job import local_parallel_pb2 as oneflow_dot_core_dot_job_dot_local__parallel__pb2
from oneflow.core.framework import user_op_attr_pb2 as oneflow_dot_core_dot_framework_dot_user__op__attr__pb2
from oneflow.core.job import module_conf_pb2 as oneflow_dot_core_dot_job_dot_module__conf__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='oneflow/core/job/scope.proto',
  package='oneflow',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1coneflow/core/job/scope.proto\x12\x07oneflow\x1a%oneflow/core/job/local_parallel.proto\x1a)oneflow/core/framework/user_op_attr.proto\x1a\"oneflow/core/job/module_conf.proto\"\x8b\x04\n\nScopeProto\x12\x1a\n\x12job_desc_symbol_id\x18\x14 \x02(\x03\x12&\n\x1e\x64\x65vice_parallel_desc_symbol_id\x18\x1e \x02(\x03\x12$\n\x1chost_parallel_desc_symbol_id\x18( \x02(\x03\x12\'\n\x19\x65nable_cpu_alternative_op\x18) \x01(\x08:\x04true\x12:\n\x17opt_local_parallel_conf\x18\x32 \x02(\x0b\x32\x19.oneflow.OptLocalParallel\x12\x1e\n\x16scope_op_name_prefixes\x18< \x03(\t\x12\x1e\n\x16parent_scope_symbol_id\x18\x46 \x01(\x03\x12\x12\n\nsession_id\x18P \x02(\x03\x12I\n\x14\x61ttr_name2attr_value\x18Z \x03(\x0b\x32+.oneflow.ScopeProto.AttrName2attrValueEntry\x12+\n\x15\x63\x61lculation_pass_name\x18\x64 \x01(\t:\x0c\x66orward_pass\x12\x13\n\x0bmodule_name\x18n \x01(\t\x1aM\n\x17\x41ttrName2attrValueEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.oneflow.AttrValue:\x02\x38\x01')
  ,
  dependencies=[oneflow_dot_core_dot_job_dot_local__parallel__pb2.DESCRIPTOR,oneflow_dot_core_dot_framework_dot_user__op__attr__pb2.DESCRIPTOR,oneflow_dot_core_dot_job_dot_module__conf__pb2.DESCRIPTOR,])




_SCOPEPROTO_ATTRNAME2ATTRVALUEENTRY = _descriptor.Descriptor(
  name='AttrName2attrValueEntry',
  full_name='oneflow.ScopeProto.AttrName2attrValueEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='oneflow.ScopeProto.AttrName2attrValueEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='oneflow.ScopeProto.AttrName2attrValueEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=606,
  serialized_end=683,
)

_SCOPEPROTO = _descriptor.Descriptor(
  name='ScopeProto',
  full_name='oneflow.ScopeProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_desc_symbol_id', full_name='oneflow.ScopeProto.job_desc_symbol_id', index=0,
      number=20, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_parallel_desc_symbol_id', full_name='oneflow.ScopeProto.device_parallel_desc_symbol_id', index=1,
      number=30, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='host_parallel_desc_symbol_id', full_name='oneflow.ScopeProto.host_parallel_desc_symbol_id', index=2,
      number=40, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enable_cpu_alternative_op', full_name='oneflow.ScopeProto.enable_cpu_alternative_op', index=3,
      number=41, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='opt_local_parallel_conf', full_name='oneflow.ScopeProto.opt_local_parallel_conf', index=4,
      number=50, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scope_op_name_prefixes', full_name='oneflow.ScopeProto.scope_op_name_prefixes', index=5,
      number=60, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parent_scope_symbol_id', full_name='oneflow.ScopeProto.parent_scope_symbol_id', index=6,
      number=70, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session_id', full_name='oneflow.ScopeProto.session_id', index=7,
      number=80, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attr_name2attr_value', full_name='oneflow.ScopeProto.attr_name2attr_value', index=8,
      number=90, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='calculation_pass_name', full_name='oneflow.ScopeProto.calculation_pass_name', index=9,
      number=100, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("forward_pass").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='module_name', full_name='oneflow.ScopeProto.module_name', index=10,
      number=110, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SCOPEPROTO_ATTRNAME2ATTRVALUEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=683,
)

_SCOPEPROTO_ATTRNAME2ATTRVALUEENTRY.fields_by_name['value'].message_type = oneflow_dot_core_dot_framework_dot_user__op__attr__pb2._ATTRVALUE
_SCOPEPROTO_ATTRNAME2ATTRVALUEENTRY.containing_type = _SCOPEPROTO
_SCOPEPROTO.fields_by_name['opt_local_parallel_conf'].message_type = oneflow_dot_core_dot_job_dot_local__parallel__pb2._OPTLOCALPARALLEL
_SCOPEPROTO.fields_by_name['attr_name2attr_value'].message_type = _SCOPEPROTO_ATTRNAME2ATTRVALUEENTRY
DESCRIPTOR.message_types_by_name['ScopeProto'] = _SCOPEPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScopeProto = _reflection.GeneratedProtocolMessageType('ScopeProto', (_message.Message,), {

  'AttrName2attrValueEntry' : _reflection.GeneratedProtocolMessageType('AttrName2attrValueEntry', (_message.Message,), {
    'DESCRIPTOR' : _SCOPEPROTO_ATTRNAME2ATTRVALUEENTRY,
    '__module__' : 'oneflow.core.job.scope_pb2'
    # @@protoc_insertion_point(class_scope:oneflow.ScopeProto.AttrName2attrValueEntry)
    })
  ,
  'DESCRIPTOR' : _SCOPEPROTO,
  '__module__' : 'oneflow.core.job.scope_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.ScopeProto)
  })
_sym_db.RegisterMessage(ScopeProto)
_sym_db.RegisterMessage(ScopeProto.AttrName2attrValueEntry)


_SCOPEPROTO_ATTRNAME2ATTRVALUEENTRY._options = None
# @@protoc_insertion_point(module_scope)
