
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-03T16:43:04+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "27852550d3d64259cf9f1b2c4e476bd5b37700ad",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
