# -*- coding: utf-8 -*-
"""data_access.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14LPkyUDmTlgJi-43-FI5TZe8IADqCitf
"""

def info():
    print("""
          data_access module has information and function to access different data files,
          - csv

          All data file has an info() function which will guide how to access the data file

          Example
          "
          data_access.csv_info()
          "
        """)

def csv_info():
        print("""
            - read csv as panda data frame
            df = pd.read_csv('c_1_001.csv', index_col = False)
            df = pd.read_csv('data.csv',skiprows=8)  # skiping first few rows
            """)