VERSION_YEAR = 2023
VERSION_MONTH = int('01')
VERSION_DAY = int('09')
VERSION_HOUR = int('12')
VERSION_MINUTE = int('25')
MAJOR_VERSION = 0
MINOR_VERSION = 13
PATCH_VERSION = 202301091225
version_date = '2023/01/09 12:25'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
