# Generated by Django 3.2 on 2022-09-08 16:10

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系方式')),
                ('introduce', models.TextField(blank=True, null=True, verbose_name='医院简介')),
                ('codenum', models.CharField(blank=True, max_length=255, null=True, verbose_name='编码')),
                ('address', models.TextField(blank=True, null=True, verbose_name='医院地址')),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='经度')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='维度')),
                ('hos_images', models.ImageField(blank=True, null=True, upload_to='images/hospital', verbose_name='医院图片')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/logo', verbose_name='logo')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='更新人')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_system.hospital', verbose_name='所属医院')),
            ],
            options={
                'verbose_name': '医院表',
                'verbose_name_plural': '医院表',
                'db_table': 'bs_hospital',
            },
        ),
        migrations.CreateModel(
            name='PositionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('codenum', models.CharField(blank=True, max_length=255, null=True, verbose_name='职称编码')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '职称表',
                'verbose_name_plural': '职称表',
                'db_table': 'bs_position_title',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系方式')),
                ('codenum', models.CharField(blank=True, max_length=255, null=True, verbose_name='科室编码')),
                ('office_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='类型')),
                ('introductory', models.TextField(blank=True, null=True, verbose_name='科室简介')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='更新人')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_system.hospital', verbose_name='所属医院')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_system.office', verbose_name='上级科室')),
            ],
            options={
                'verbose_name': '科室表',
                'verbose_name_plural': '科室表',
                'db_table': 'bs_office',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系方式')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='工号')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='职位')),
                ('gender', models.CharField(blank=True, choices=[(1, '男'), (0, '女')], max_length=2, null=True, verbose_name='性别')),
                ('nation', models.CharField(blank=True, max_length=255, null=True, verbose_name='民族')),
                ('idnum', models.CharField(blank=True, max_length=255, null=True, verbose_name='身份证号')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/doctor', verbose_name='医生照片')),
                ('des', models.TextField(blank=True, null=True, verbose_name='医生描述')),
                ('doc_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_system.positiontitle', verbose_name='职称')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_system.hospital', verbose_name='所属医院')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_system.office', verbose_name='所属科室')),
            ],
            options={
                'verbose_name': '医生表',
                'verbose_name_plural': '医生表',
                'db_table': 'bs_doctor',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='密码')),
                ('last_login', models.DateField(blank=True, null=True, verbose_name='上次登录时间')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='是否是超管')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系方式')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('gender', models.CharField(blank=True, choices=[(1, '男'), (0, '女')], max_length=2, null=True, verbose_name='性别')),
                ('idcardnum', models.CharField(blank=True, max_length=255, null=True, verbose_name='身份证号')),
                ('order_by', models.IntegerField(blank=True, default=1, null=True, verbose_name='排序')),
                ('avatar_url', models.ImageField(blank=True, null=True, upload_to='images/user', verbose_name='医生照片')),
                ('default_group_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='默认角色')),
                ('allow_office', models.CharField(blank=True, max_length=255, null=True, verbose_name='可操作科室')),
                ('note', models.TextField(blank=True, null=True, verbose_name='注释说明')),
                ('created_user', models.CharField(blank=True, max_length=255, null=True, verbose_name='创建人')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_system.hospital', verbose_name='所属医院')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_system.office', verbose_name='所属科室')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
                ('user_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_system.positiontitle', verbose_name='职称')),
            ],
            options={
                'verbose_name': '用户表',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
