# Generated by Django 3.2 on 2022-09-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_system', '0011_alter_expensestandard_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensestandard',
            name='fees',
        ),
    ]
