# Generated by Django 3.2 on 2022-09-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_system', '0018_user_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('belong_model', models.CharField(max_length=100, verbose_name='所属model')),
                ('belong_id', models.CharField(max_length=100, verbose_name='所属id')),
                ('small_image', models.ImageField(upload_to=('images/%s', models.CharField(max_length=100, verbose_name='所属model')), verbose_name='缩略图')),
                ('big_image', models.ImageField(upload_to=('images/%s', models.CharField(max_length=100, verbose_name='所属model')), verbose_name='原图')),
            ],
            options={
                'verbose_name': '图片存放',
                'verbose_name_plural': '图片存放',
                'db_table': 'bs_images_upload',
            },
        ),
    ]
