# Generated by Django 3.2 on 2022-09-26 10:23

import base_system.models
import tools_collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_system', '0021_auto_20220923_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesupload',
            name='big_image',
            field=models.ImageField(upload_to=tools_collection.models.get_image_path, verbose_name='原图'),
        ),
        migrations.AlterField(
            model_name='imagesupload',
            name='small_image',
            field=models.ImageField(upload_to=tools_collection.models.get_image_path, verbose_name='缩略图'),
        ),
    ]
