# Generated by Django 3.2 on 2022-10-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_system', '0024_auto_20220927_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountproviders',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='accountproviders',
            name='platform_provider',
        ),
        migrations.DeleteModel(
            name='ElectronicHealthCard',
        ),
        migrations.DeleteModel(
            name='AccountProviders',
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
        migrations.DeleteModel(
            name='PlatformProvider',
        ),
    ]
