# Generated by Django 3.2 on 2022-11-10 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_system', '0030_auto_20221109_1700'),
        ('base_system', '0031_rename_drug_cod_drugdirectory_drug_code'),
    ]

    operations = [
    ]
