# Generated by Django 3.2 on 2022-12-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_system', '0041_auto_20221213_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extragroup',
            name='hospital',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='base_system.hospital', verbose_name='所属医院'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extragroup',
            name='role_code',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='角色代码'),
            preserve_default=False,
        ),
    ]
