# Generated by Django 3.2 on 2022-12-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_system', '0042_auto_20221214_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='logo',
            field=models.CharField(default='hospital_logo', max_length=100, verbose_name='logo'),
        ),
    ]
