from .create_template import handle_create_template
from .delete_template import handle_delete_template
from .edit_template import handle_edit_template
from .generate_project import handle_generate_project
from .template_info import handle_template_info
