
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-06T15:56:55+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d827271f80601c4e83401af5e547254b0b33a4fa",
 "version": "v1.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
