
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-04T16:30:08-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "5a80f34f9208118513d9c98e831260c2db38ef9f",
 "version": "0.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
