
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-04T15:29:09-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "77e7143f58d545b99598653254defad1a8e2f12c",
 "version": "6.0.0-alpha1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
