# Generated by Django 4.0.7 on 2022-08-23 12:49

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0016_character_names_are_not_unique"),
        ("fleetfinder", "0004_alter_fleet_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fleet",
            name="fleet_commander",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fleetfinder_fleet_commander",
                to="eveonline.evecharacter",
            ),
        ),
    ]
