# -*- coding: utf-8 -*-
from setuptools import setup

package_dir = \
{'': '..'}

packages = \
['ayaka_games',
 'ayaka_games.plugins',
 'ayaka_games.plugins.data',
 'ayaka_games.plugins.extra']

package_data = \
{'': ['*'],
 'ayaka_games': ['.git/*',
                 '.git/hooks/*',
                 '.git/info/*',
                 '.git/logs/*',
                 '.git/logs/refs/heads/*',
                 '.git/logs/refs/remotes/origin/*',
                 '.git/objects/00/*',
                 '.git/objects/02/*',
                 '.git/objects/03/*',
                 '.git/objects/04/*',
                 '.git/objects/05/*',
                 '.git/objects/07/*',
                 '.git/objects/08/*',
                 '.git/objects/09/*',
                 '.git/objects/0a/*',
                 '.git/objects/0b/*',
                 '.git/objects/0c/*',
                 '.git/objects/0d/*',
                 '.git/objects/0e/*',
                 '.git/objects/0f/*',
                 '.git/objects/10/*',
                 '.git/objects/11/*',
                 '.git/objects/12/*',
                 '.git/objects/13/*',
                 '.git/objects/15/*',
                 '.git/objects/16/*',
                 '.git/objects/17/*',
                 '.git/objects/18/*',
                 '.git/objects/19/*',
                 '.git/objects/1a/*',
                 '.git/objects/1b/*',
                 '.git/objects/1c/*',
                 '.git/objects/1d/*',
                 '.git/objects/1e/*',
                 '.git/objects/1f/*',
                 '.git/objects/20/*',
                 '.git/objects/21/*',
                 '.git/objects/22/*',
                 '.git/objects/23/*',
                 '.git/objects/25/*',
                 '.git/objects/26/*',
                 '.git/objects/27/*',
                 '.git/objects/2a/*',
                 '.git/objects/2b/*',
                 '.git/objects/2c/*',
                 '.git/objects/2e/*',
                 '.git/objects/2f/*',
                 '.git/objects/30/*',
                 '.git/objects/31/*',
                 '.git/objects/32/*',
                 '.git/objects/33/*',
                 '.git/objects/34/*',
                 '.git/objects/35/*',
                 '.git/objects/36/*',
                 '.git/objects/37/*',
                 '.git/objects/39/*',
                 '.git/objects/3a/*',
                 '.git/objects/3b/*',
                 '.git/objects/3c/*',
                 '.git/objects/3d/*',
                 '.git/objects/3e/*',
                 '.git/objects/3f/*',
                 '.git/objects/40/*',
                 '.git/objects/41/*',
                 '.git/objects/42/*',
                 '.git/objects/43/*',
                 '.git/objects/44/*',
                 '.git/objects/45/*',
                 '.git/objects/46/*',
                 '.git/objects/47/*',
                 '.git/objects/48/*',
                 '.git/objects/49/*',
                 '.git/objects/4a/*',
                 '.git/objects/4b/*',
                 '.git/objects/4c/*',
                 '.git/objects/4d/*',
                 '.git/objects/4e/*',
                 '.git/objects/4f/*',
                 '.git/objects/50/*',
                 '.git/objects/51/*',
                 '.git/objects/53/*',
                 '.git/objects/54/*',
                 '.git/objects/55/*',
                 '.git/objects/56/*',
                 '.git/objects/57/*',
                 '.git/objects/58/*',
                 '.git/objects/59/*',
                 '.git/objects/5a/*',
                 '.git/objects/5b/*',
                 '.git/objects/5c/*',
                 '.git/objects/5d/*',
                 '.git/objects/5e/*',
                 '.git/objects/5f/*',
                 '.git/objects/60/*',
                 '.git/objects/61/*',
                 '.git/objects/62/*',
                 '.git/objects/63/*',
                 '.git/objects/64/*',
                 '.git/objects/65/*',
                 '.git/objects/66/*',
                 '.git/objects/67/*',
                 '.git/objects/68/*',
                 '.git/objects/69/*',
                 '.git/objects/6a/*',
                 '.git/objects/6b/*',
                 '.git/objects/6c/*',
                 '.git/objects/6d/*',
                 '.git/objects/6e/*',
                 '.git/objects/6f/*',
                 '.git/objects/70/*',
                 '.git/objects/71/*',
                 '.git/objects/72/*',
                 '.git/objects/73/*',
                 '.git/objects/74/*',
                 '.git/objects/75/*',
                 '.git/objects/76/*',
                 '.git/objects/77/*',
                 '.git/objects/78/*',
                 '.git/objects/79/*',
                 '.git/objects/7a/*',
                 '.git/objects/7b/*',
                 '.git/objects/7d/*',
                 '.git/objects/7f/*',
                 '.git/objects/80/*',
                 '.git/objects/81/*',
                 '.git/objects/82/*',
                 '.git/objects/83/*',
                 '.git/objects/84/*',
                 '.git/objects/85/*',
                 '.git/objects/86/*',
                 '.git/objects/87/*',
                 '.git/objects/88/*',
                 '.git/objects/89/*',
                 '.git/objects/8a/*',
                 '.git/objects/8b/*',
                 '.git/objects/8c/*',
                 '.git/objects/8d/*',
                 '.git/objects/8e/*',
                 '.git/objects/8f/*',
                 '.git/objects/91/*',
                 '.git/objects/92/*',
                 '.git/objects/93/*',
                 '.git/objects/95/*',
                 '.git/objects/96/*',
                 '.git/objects/97/*',
                 '.git/objects/98/*',
                 '.git/objects/99/*',
                 '.git/objects/9a/*',
                 '.git/objects/9b/*',
                 '.git/objects/9c/*',
                 '.git/objects/9d/*',
                 '.git/objects/9e/*',
                 '.git/objects/9f/*',
                 '.git/objects/a0/*',
                 '.git/objects/a1/*',
                 '.git/objects/a2/*',
                 '.git/objects/a3/*',
                 '.git/objects/a4/*',
                 '.git/objects/a5/*',
                 '.git/objects/a6/*',
                 '.git/objects/a7/*',
                 '.git/objects/a8/*',
                 '.git/objects/a9/*',
                 '.git/objects/ab/*',
                 '.git/objects/ac/*',
                 '.git/objects/ad/*',
                 '.git/objects/ae/*',
                 '.git/objects/af/*',
                 '.git/objects/b0/*',
                 '.git/objects/b1/*',
                 '.git/objects/b2/*',
                 '.git/objects/b3/*',
                 '.git/objects/b4/*',
                 '.git/objects/b5/*',
                 '.git/objects/b6/*',
                 '.git/objects/b8/*',
                 '.git/objects/b9/*',
                 '.git/objects/ba/*',
                 '.git/objects/bb/*',
                 '.git/objects/bc/*',
                 '.git/objects/bd/*',
                 '.git/objects/be/*',
                 '.git/objects/bf/*',
                 '.git/objects/c0/*',
                 '.git/objects/c1/*',
                 '.git/objects/c2/*',
                 '.git/objects/c3/*',
                 '.git/objects/c4/*',
                 '.git/objects/c5/*',
                 '.git/objects/c6/*',
                 '.git/objects/c7/*',
                 '.git/objects/c8/*',
                 '.git/objects/c9/*',
                 '.git/objects/ca/*',
                 '.git/objects/cb/*',
                 '.git/objects/cc/*',
                 '.git/objects/cd/*',
                 '.git/objects/ce/*',
                 '.git/objects/cf/*',
                 '.git/objects/d0/*',
                 '.git/objects/d2/*',
                 '.git/objects/d3/*',
                 '.git/objects/d4/*',
                 '.git/objects/d5/*',
                 '.git/objects/d6/*',
                 '.git/objects/d7/*',
                 '.git/objects/d8/*',
                 '.git/objects/d9/*',
                 '.git/objects/da/*',
                 '.git/objects/db/*',
                 '.git/objects/dc/*',
                 '.git/objects/dd/*',
                 '.git/objects/df/*',
                 '.git/objects/e0/*',
                 '.git/objects/e1/*',
                 '.git/objects/e2/*',
                 '.git/objects/e3/*',
                 '.git/objects/e4/*',
                 '.git/objects/e5/*',
                 '.git/objects/e6/*',
                 '.git/objects/e7/*',
                 '.git/objects/e8/*',
                 '.git/objects/ea/*',
                 '.git/objects/eb/*',
                 '.git/objects/ed/*',
                 '.git/objects/ee/*',
                 '.git/objects/ef/*',
                 '.git/objects/f0/*',
                 '.git/objects/f1/*',
                 '.git/objects/f2/*',
                 '.git/objects/f3/*',
                 '.git/objects/f5/*',
                 '.git/objects/f6/*',
                 '.git/objects/f7/*',
                 '.git/objects/f8/*',
                 '.git/objects/f9/*',
                 '.git/objects/fa/*',
                 '.git/objects/fb/*',
                 '.git/objects/fc/*',
                 '.git/objects/fe/*',
                 '.git/objects/ff/*',
                 '.git/refs/heads/*',
                 '.git/refs/remotes/origin/*',
                 'dist/*'],
 'ayaka_games.plugins': ['data/calc_24/*', 'data/dragon/*']}

install_requires = \
['nonebot-plugin-ayaka>=1.0.1b1,<2.0.0', 'pypinyin>=0.47.1,<0.48.0']

setup_kwargs = {
    'name': 'nonebot-plugin-ayaka-games',
    'version': '0.5.1b2',
    'description': 'ayaka小游戏合集',
    'long_description': '<div align="center">\n\n# ayaka文字小游戏合集 v0.5.1b2\n\n基于[ayaka](https://github.com/bridgeL/nonebot-plugin-ayaka)开发的文字小游戏合集\n\n开发进度 9/10，还剩1个小游戏等待构思\n\n**特别感谢**  [@灯夜](https://github.com/lunexnocty/Meiri) 大佬的插件蛮好玩的~\n\n</div>\n\n## 文档\n\nhttps://bridgel.github.io/ayaka_doc/latest/games/\n\n',
    'author': 'Su',
    'author_email': 'wxlxy316@163.com',
    'maintainer': 'None',
    'maintainer_email': 'None',
    'url': 'https://github.com/bridgeL/nonebot-plugin-ayaka-games',
    'package_dir': package_dir,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.10,<4.0',
}


setup(**setup_kwargs)
