
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-04T13:48:32+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "35bf49f0229d3ccb9f0b3c201a688c39dac86cf5",
 "version": "0.2.58.post0.dev52"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
