
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-08T02:27:00+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "95af1843825365f757462d2023659697169947d4",
 "version": "0.5.dev2302"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
