// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/job/job.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_oneflow_2fcore_2fjob_2fjob_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_oneflow_2fcore_2fjob_2fjob_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include "oneflow/core/job/dlnet_conf.pb.h"
#include "oneflow/core/job/placement.pb.h"
#include "oneflow/core/job/job_conf.pb.h"
#include "oneflow/core/register/logical_blob_id.pb.h"
#include "oneflow/core/register/op_blob_arg.pb.h"
#include "oneflow/core/register/blob_desc.pb.h"
#include "oneflow/core/operator/op_conf.pb.h"
#include "oneflow/core/job/sbp_parallel.pb.h"
#include "oneflow/core/job/module_conf.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_oneflow_2fcore_2fjob_2fjob_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_oneflow_2fcore_2fjob_2fjob_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[13]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_oneflow_2fcore_2fjob_2fjob_2eproto;
namespace oneflow {
class Job;
class JobDefaultTypeInternal;
extern JobDefaultTypeInternal _Job_default_instance_;
class JobHelperConf;
class JobHelperConfDefaultTypeInternal;
extern JobHelperConfDefaultTypeInternal _JobHelperConf_default_instance_;
class JobHelperConf_Lbn2logicalBlobDescEntry_DoNotUse;
class JobHelperConf_Lbn2logicalBlobDescEntry_DoNotUseDefaultTypeInternal;
extern JobHelperConf_Lbn2logicalBlobDescEntry_DoNotUseDefaultTypeInternal _JobHelperConf_Lbn2logicalBlobDescEntry_DoNotUse_default_instance_;
class JobHelperConf_Lbn2logicalObjectIdEntry_DoNotUse;
class JobHelperConf_Lbn2logicalObjectIdEntry_DoNotUseDefaultTypeInternal;
extern JobHelperConf_Lbn2logicalObjectIdEntry_DoNotUseDefaultTypeInternal _JobHelperConf_Lbn2logicalObjectIdEntry_DoNotUse_default_instance_;
class JobHelperConf_OpName2argSignatureEntry_DoNotUse;
class JobHelperConf_OpName2argSignatureEntry_DoNotUseDefaultTypeInternal;
extern JobHelperConf_OpName2argSignatureEntry_DoNotUseDefaultTypeInternal _JobHelperConf_OpName2argSignatureEntry_DoNotUse_default_instance_;
class JobHelperConf_Tag2lbiRelationsEntry_DoNotUse;
class JobHelperConf_Tag2lbiRelationsEntry_DoNotUseDefaultTypeInternal;
extern JobHelperConf_Tag2lbiRelationsEntry_DoNotUseDefaultTypeInternal _JobHelperConf_Tag2lbiRelationsEntry_DoNotUse_default_instance_;
class JobHelperConf_Tag2opNameRelationsEntry_DoNotUse;
class JobHelperConf_Tag2opNameRelationsEntry_DoNotUseDefaultTypeInternal;
extern JobHelperConf_Tag2opNameRelationsEntry_DoNotUseDefaultTypeInternal _JobHelperConf_Tag2opNameRelationsEntry_DoNotUse_default_instance_;
class JobParallelViewConf;
class JobParallelViewConfDefaultTypeInternal;
extern JobParallelViewConfDefaultTypeInternal _JobParallelViewConf_default_instance_;
class JobParallelViewConf_OpName2isLocalParallelViewEntry_DoNotUse;
class JobParallelViewConf_OpName2isLocalParallelViewEntry_DoNotUseDefaultTypeInternal;
extern JobParallelViewConf_OpName2isLocalParallelViewEntry_DoNotUseDefaultTypeInternal _JobParallelViewConf_OpName2isLocalParallelViewEntry_DoNotUse_default_instance_;
class JobParallelViewConf_OpName2ndSbpSignatureConfEntry_DoNotUse;
class JobParallelViewConf_OpName2ndSbpSignatureConfEntry_DoNotUseDefaultTypeInternal;
extern JobParallelViewConf_OpName2ndSbpSignatureConfEntry_DoNotUseDefaultTypeInternal _JobParallelViewConf_OpName2ndSbpSignatureConfEntry_DoNotUse_default_instance_;
class JobParallelViewConf_OpName2sbpSignatureConfEntry_DoNotUse;
class JobParallelViewConf_OpName2sbpSignatureConfEntry_DoNotUseDefaultTypeInternal;
extern JobParallelViewConf_OpName2sbpSignatureConfEntry_DoNotUseDefaultTypeInternal _JobParallelViewConf_OpName2sbpSignatureConfEntry_DoNotUse_default_instance_;
class Job_ModuleName2moduleConfEntry_DoNotUse;
class Job_ModuleName2moduleConfEntry_DoNotUseDefaultTypeInternal;
extern Job_ModuleName2moduleConfEntry_DoNotUseDefaultTypeInternal _Job_ModuleName2moduleConfEntry_DoNotUse_default_instance_;
class MergedLogicalChainIdGroup;
class MergedLogicalChainIdGroupDefaultTypeInternal;
extern MergedLogicalChainIdGroupDefaultTypeInternal _MergedLogicalChainIdGroup_default_instance_;
}  // namespace oneflow
PROTOBUF_NAMESPACE_OPEN
template<> ::oneflow::Job* Arena::CreateMaybeMessage<::oneflow::Job>(Arena*);
template<> ::oneflow::JobHelperConf* Arena::CreateMaybeMessage<::oneflow::JobHelperConf>(Arena*);
template<> ::oneflow::JobHelperConf_Lbn2logicalBlobDescEntry_DoNotUse* Arena::CreateMaybeMessage<::oneflow::JobHelperConf_Lbn2logicalBlobDescEntry_DoNotUse>(Arena*);
template<> ::oneflow::JobHelperConf_Lbn2logicalObjectIdEntry_DoNotUse* Arena::CreateMaybeMessage<::oneflow::JobHelperConf_Lbn2logicalObjectIdEntry_DoNotUse>(Arena*);
template<> ::oneflow::JobHelperConf_OpName2argSignatureEntry_DoNotUse* Arena::CreateMaybeMessage<::oneflow::JobHelperConf_OpName2argSignatureEntry_DoNotUse>(Arena*);
template<> ::oneflow::JobHelperConf_Tag2lbiRelationsEntry_DoNotUse* Arena::CreateMaybeMessage<::oneflow::JobHelperConf_Tag2lbiRelationsEntry_DoNotUse>(Arena*);
template<> ::oneflow::JobHelperConf_Tag2opNameRelationsEntry_DoNotUse* Arena::CreateMaybeMessage<::oneflow::JobHelperConf_Tag2opNameRelationsEntry_DoNotUse>(Arena*);
template<> ::oneflow::JobParallelViewConf* Arena::CreateMaybeMessage<::oneflow::JobParallelViewConf>(Arena*);
template<> ::oneflow::JobParallelViewConf_OpName2isLocalParallelViewEntry_DoNotUse* Arena::CreateMaybeMessage<::oneflow::JobParallelViewConf_OpName2isLocalParallelViewEntry_DoNotUse>(Arena*);
template<> ::oneflow::JobParallelViewConf_OpName2ndSbpSignatureConfEntry_DoNotUse* Arena::CreateMaybeMessage<::oneflow::JobParallelViewConf_OpName2ndSbpSignatureConfEntry_DoNotUse>(Arena*);
template<> ::oneflow::JobParallelViewConf_OpName2sbpSignatureConfEntry_DoNotUse* Arena::CreateMaybeMessage<::oneflow::JobParallelViewConf_OpName2sbpSignatureConfEntry_DoNotUse>(Arena*);
template<> ::oneflow::Job_ModuleName2moduleConfEntry_DoNotUse* Arena::CreateMaybeMessage<::oneflow::Job_ModuleName2moduleConfEntry_DoNotUse>(Arena*);
template<> ::oneflow::MergedLogicalChainIdGroup* Arena::CreateMaybeMessage<::oneflow::MergedLogicalChainIdGroup>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace oneflow {

// ===================================================================

class JobParallelViewConf_OpName2sbpSignatureConfEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<JobParallelViewConf_OpName2sbpSignatureConfEntry_DoNotUse, 
    std::string, ::oneflow::SbpSignature,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<JobParallelViewConf_OpName2sbpSignatureConfEntry_DoNotUse, 
    std::string, ::oneflow::SbpSignature,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  JobParallelViewConf_OpName2sbpSignatureConfEntry_DoNotUse();
  JobParallelViewConf_OpName2sbpSignatureConfEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const JobParallelViewConf_OpName2sbpSignatureConfEntry_DoNotUse& other);
  static const JobParallelViewConf_OpName2sbpSignatureConfEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const JobParallelViewConf_OpName2sbpSignatureConfEntry_DoNotUse*>(&_JobParallelViewConf_OpName2sbpSignatureConfEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
#ifndef NDEBUG
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
       s->data(), s->size(), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "oneflow.JobParallelViewConf.OpName2sbpSignatureConfEntry.key");
#endif
    return true;
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_oneflow_2fcore_2fjob_2fjob_2eproto);
    return ::descriptor_table_oneflow_2fcore_2fjob_2fjob_2eproto.file_level_metadata[0];
  }

  public:
};

// -------------------------------------------------------------------

class JobParallelViewConf_OpName2isLocalParallelViewEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<JobParallelViewConf_OpName2isLocalParallelViewEntry_DoNotUse, 
    std::string, bool,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_BOOL,
    0 > {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<JobParallelViewConf_OpName2isLocalParallelViewEntry_DoNotUse, 
    std::string, bool,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_BOOL,
    0 > SuperType;
  JobParallelViewConf_OpName2isLocalParallelViewEntry_DoNotUse();
  JobParallelViewConf_OpName2isLocalParallelViewEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const JobParallelViewConf_OpName2isLocalParallelViewEntry_DoNotUse& other);
  static const JobParallelViewConf_OpName2isLocalParallelViewEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const JobParallelViewConf_OpName2isLocalParallelViewEntry_DoNotUse*>(&_JobParallelViewConf_OpName2isLocalParallelViewEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
#ifndef NDEBUG
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
       s->data(), s->size(), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "oneflow.JobParallelViewConf.OpName2isLocalParallelViewEntry.key");
#endif
    return true;
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_oneflow_2fcore_2fjob_2fjob_2eproto);
    return ::descriptor_table_oneflow_2fcore_2fjob_2fjob_2eproto.file_level_metadata[1];
  }

  public:
};

// -------------------------------------------------------------------

class JobParallelViewConf_OpName2ndSbpSignatureConfEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<JobParallelViewConf_OpName2ndSbpSignatureConfEntry_DoNotUse, 
    std::string, ::oneflow::NdSbpSignature,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<JobParallelViewConf_OpName2ndSbpSignatureConfEntry_DoNotUse, 
    std::string, ::oneflow::NdSbpSignature,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  JobParallelViewConf_OpName2ndSbpSignatureConfEntry_DoNotUse();
  JobParallelViewConf_OpName2ndSbpSignatureConfEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const JobParallelViewConf_OpName2ndSbpSignatureConfEntry_DoNotUse& other);
  static const JobParallelViewConf_OpName2ndSbpSignatureConfEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const JobParallelViewConf_OpName2ndSbpSignatureConfEntry_DoNotUse*>(&_JobParallelViewConf_OpName2ndSbpSignatureConfEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
#ifndef NDEBUG
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
       s->data(), s->size(), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "oneflow.JobParallelViewConf.OpName2ndSbpSignatureConfEntry.key");
#endif
    return true;
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_oneflow_2fcore_2fjob_2fjob_2eproto);
    return ::descriptor_table_oneflow_2fcore_2fjob_2fjob_2eproto.file_level_metadata[2];
  }

  public:
};

// -------------------------------------------------------------------

class JobParallelViewConf :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:oneflow.JobParallelViewConf) */ {
 public:
  JobParallelViewConf();
  virtual ~JobParallelViewConf();

  JobParallelViewConf(const JobParallelViewConf& from);
  JobParallelViewConf(JobParallelViewConf&& from) noexcept
    : JobParallelViewConf() {
    *this = ::std::move(from);
  }

  inline JobParallelViewConf& operator=(const JobParallelViewConf& from) {
    CopyFrom(from);
    return *this;
  }
  inline JobParallelViewConf& operator=(JobParallelViewConf&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const JobParallelViewConf& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const JobParallelViewConf* internal_default_instance() {
    return reinterpret_cast<const JobParallelViewConf*>(
               &_JobParallelViewConf_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(JobParallelViewConf& a, JobParallelViewConf& b) {
    a.Swap(&b);
  }
  inline void Swap(JobParallelViewConf* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline JobParallelViewConf* New() const final {
    return CreateMaybeMessage<JobParallelViewConf>(nullptr);
  }

  JobParallelViewConf* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<JobParallelViewConf>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const JobParallelViewConf& from);
  void MergeFrom(const JobParallelViewConf& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JobParallelViewConf* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oneflow.JobParallelViewConf";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_oneflow_2fcore_2fjob_2fjob_2eproto);
    return ::descriptor_table_oneflow_2fcore_2fjob_2fjob_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kOpName2SbpSignatureConfFieldNumber = 1,
    kOpName2IsLocalParallelViewFieldNumber = 2,
    kOpName2NdSbpSignatureConfFieldNumber = 3,
  };
  // map<string, .oneflow.SbpSignature> op_name2sbp_signature_conf = 1;
  int op_name2sbp_signature_conf_size() const;
  void clear_op_name2sbp_signature_conf();
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::SbpSignature >&
      op_name2sbp_signature_conf() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::SbpSignature >*
      mutable_op_name2sbp_signature_conf();

  // map<string, bool> op_name2is_local_parallel_view = 2;
  int op_name2is_local_parallel_view_size() const;
  void clear_op_name2is_local_parallel_view();
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, bool >&
      op_name2is_local_parallel_view() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, bool >*
      mutable_op_name2is_local_parallel_view();

  // map<string, .oneflow.NdSbpSignature> op_name2nd_sbp_signature_conf = 3;
  int op_name2nd_sbp_signature_conf_size() const;
  void clear_op_name2nd_sbp_signature_conf();
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::NdSbpSignature >&
      op_name2nd_sbp_signature_conf() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::NdSbpSignature >*
      mutable_op_name2nd_sbp_signature_conf();

  // @@protoc_insertion_point(class_scope:oneflow.JobParallelViewConf)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      JobParallelViewConf_OpName2sbpSignatureConfEntry_DoNotUse,
      std::string, ::oneflow::SbpSignature,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
      0 > op_name2sbp_signature_conf_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      JobParallelViewConf_OpName2isLocalParallelViewEntry_DoNotUse,
      std::string, bool,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_BOOL,
      0 > op_name2is_local_parallel_view_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      JobParallelViewConf_OpName2ndSbpSignatureConfEntry_DoNotUse,
      std::string, ::oneflow::NdSbpSignature,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
      0 > op_name2nd_sbp_signature_conf_;
  friend struct ::TableStruct_oneflow_2fcore_2fjob_2fjob_2eproto;
};
// -------------------------------------------------------------------

class JobHelperConf_Tag2lbiRelationsEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<JobHelperConf_Tag2lbiRelationsEntry_DoNotUse, 
    std::string, ::oneflow::LogicalBlobIdPairs,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<JobHelperConf_Tag2lbiRelationsEntry_DoNotUse, 
    std::string, ::oneflow::LogicalBlobIdPairs,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  JobHelperConf_Tag2lbiRelationsEntry_DoNotUse();
  JobHelperConf_Tag2lbiRelationsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const JobHelperConf_Tag2lbiRelationsEntry_DoNotUse& other);
  static const JobHelperConf_Tag2lbiRelationsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const JobHelperConf_Tag2lbiRelationsEntry_DoNotUse*>(&_JobHelperConf_Tag2lbiRelationsEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
#ifndef NDEBUG
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
       s->data(), s->size(), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "oneflow.JobHelperConf.Tag2lbiRelationsEntry.key");
#endif
    return true;
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_oneflow_2fcore_2fjob_2fjob_2eproto);
    return ::descriptor_table_oneflow_2fcore_2fjob_2fjob_2eproto.file_level_metadata[4];
  }

  public:
};

// -------------------------------------------------------------------

class JobHelperConf_Tag2opNameRelationsEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<JobHelperConf_Tag2opNameRelationsEntry_DoNotUse, 
    std::string, ::oneflow::OpNameRelations,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<JobHelperConf_Tag2opNameRelationsEntry_DoNotUse, 
    std::string, ::oneflow::OpNameRelations,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  JobHelperConf_Tag2opNameRelationsEntry_DoNotUse();
  JobHelperConf_Tag2opNameRelationsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const JobHelperConf_Tag2opNameRelationsEntry_DoNotUse& other);
  static const JobHelperConf_Tag2opNameRelationsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const JobHelperConf_Tag2opNameRelationsEntry_DoNotUse*>(&_JobHelperConf_Tag2opNameRelationsEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
#ifndef NDEBUG
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
       s->data(), s->size(), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "oneflow.JobHelperConf.Tag2opNameRelationsEntry.key");
#endif
    return true;
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_oneflow_2fcore_2fjob_2fjob_2eproto);
    return ::descriptor_table_oneflow_2fcore_2fjob_2fjob_2eproto.file_level_metadata[5];
  }

  public:
};

// -------------------------------------------------------------------

class JobHelperConf_Lbn2logicalBlobDescEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<JobHelperConf_Lbn2logicalBlobDescEntry_DoNotUse, 
    std::string, ::oneflow::BlobDescProto,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<JobHelperConf_Lbn2logicalBlobDescEntry_DoNotUse, 
    std::string, ::oneflow::BlobDescProto,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  JobHelperConf_Lbn2logicalBlobDescEntry_DoNotUse();
  JobHelperConf_Lbn2logicalBlobDescEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const JobHelperConf_Lbn2logicalBlobDescEntry_DoNotUse& other);
  static const JobHelperConf_Lbn2logicalBlobDescEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const JobHelperConf_Lbn2logicalBlobDescEntry_DoNotUse*>(&_JobHelperConf_Lbn2logicalBlobDescEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
#ifndef NDEBUG
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
       s->data(), s->size(), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "oneflow.JobHelperConf.Lbn2logicalBlobDescEntry.key");
#endif
    return true;
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_oneflow_2fcore_2fjob_2fjob_2eproto);
    return ::descriptor_table_oneflow_2fcore_2fjob_2fjob_2eproto.file_level_metadata[6];
  }

  public:
};

// -------------------------------------------------------------------

class JobHelperConf_Lbn2logicalObjectIdEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<JobHelperConf_Lbn2logicalObjectIdEntry_DoNotUse, 
    std::string, ::PROTOBUF_NAMESPACE_ID::int64,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64,
    0 > {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<JobHelperConf_Lbn2logicalObjectIdEntry_DoNotUse, 
    std::string, ::PROTOBUF_NAMESPACE_ID::int64,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64,
    0 > SuperType;
  JobHelperConf_Lbn2logicalObjectIdEntry_DoNotUse();
  JobHelperConf_Lbn2logicalObjectIdEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const JobHelperConf_Lbn2logicalObjectIdEntry_DoNotUse& other);
  static const JobHelperConf_Lbn2logicalObjectIdEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const JobHelperConf_Lbn2logicalObjectIdEntry_DoNotUse*>(&_JobHelperConf_Lbn2logicalObjectIdEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
#ifndef NDEBUG
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
       s->data(), s->size(), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "oneflow.JobHelperConf.Lbn2logicalObjectIdEntry.key");
#endif
    return true;
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_oneflow_2fcore_2fjob_2fjob_2eproto);
    return ::descriptor_table_oneflow_2fcore_2fjob_2fjob_2eproto.file_level_metadata[7];
  }

  public:
};

// -------------------------------------------------------------------

class JobHelperConf_OpName2argSignatureEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<JobHelperConf_OpName2argSignatureEntry_DoNotUse, 
    std::string, ::oneflow::ArgSignature,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<JobHelperConf_OpName2argSignatureEntry_DoNotUse, 
    std::string, ::oneflow::ArgSignature,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  JobHelperConf_OpName2argSignatureEntry_DoNotUse();
  JobHelperConf_OpName2argSignatureEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const JobHelperConf_OpName2argSignatureEntry_DoNotUse& other);
  static const JobHelperConf_OpName2argSignatureEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const JobHelperConf_OpName2argSignatureEntry_DoNotUse*>(&_JobHelperConf_OpName2argSignatureEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
#ifndef NDEBUG
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
       s->data(), s->size(), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "oneflow.JobHelperConf.OpName2argSignatureEntry.key");
#endif
    return true;
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_oneflow_2fcore_2fjob_2fjob_2eproto);
    return ::descriptor_table_oneflow_2fcore_2fjob_2fjob_2eproto.file_level_metadata[8];
  }

  public:
};

// -------------------------------------------------------------------

class JobHelperConf :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:oneflow.JobHelperConf) */ {
 public:
  JobHelperConf();
  virtual ~JobHelperConf();

  JobHelperConf(const JobHelperConf& from);
  JobHelperConf(JobHelperConf&& from) noexcept
    : JobHelperConf() {
    *this = ::std::move(from);
  }

  inline JobHelperConf& operator=(const JobHelperConf& from) {
    CopyFrom(from);
    return *this;
  }
  inline JobHelperConf& operator=(JobHelperConf&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const JobHelperConf& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const JobHelperConf* internal_default_instance() {
    return reinterpret_cast<const JobHelperConf*>(
               &_JobHelperConf_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  friend void swap(JobHelperConf& a, JobHelperConf& b) {
    a.Swap(&b);
  }
  inline void Swap(JobHelperConf* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline JobHelperConf* New() const final {
    return CreateMaybeMessage<JobHelperConf>(nullptr);
  }

  JobHelperConf* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<JobHelperConf>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const JobHelperConf& from);
  void MergeFrom(const JobHelperConf& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JobHelperConf* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oneflow.JobHelperConf";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_oneflow_2fcore_2fjob_2fjob_2eproto);
    return ::descriptor_table_oneflow_2fcore_2fjob_2fjob_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kTag2LbiRelationsFieldNumber = 1,
    kTag2OpNameRelationsFieldNumber = 2,
    kLbn2LogicalBlobDescFieldNumber = 4,
    kLbn2LogicalObjectIdFieldNumber = 5,
    kOpName2ArgSignatureFieldNumber = 9,
  };
  // map<string, .oneflow.LogicalBlobIdPairs> tag2lbi_relations = 1;
  int tag2lbi_relations_size() const;
  void clear_tag2lbi_relations();
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::LogicalBlobIdPairs >&
      tag2lbi_relations() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::LogicalBlobIdPairs >*
      mutable_tag2lbi_relations();

  // map<string, .oneflow.OpNameRelations> tag2op_name_relations = 2;
  int tag2op_name_relations_size() const;
  void clear_tag2op_name_relations();
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::OpNameRelations >&
      tag2op_name_relations() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::OpNameRelations >*
      mutable_tag2op_name_relations();

  // map<string, .oneflow.BlobDescProto> lbn2logical_blob_desc = 4;
  int lbn2logical_blob_desc_size() const;
  void clear_lbn2logical_blob_desc();
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::BlobDescProto >&
      lbn2logical_blob_desc() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::BlobDescProto >*
      mutable_lbn2logical_blob_desc();

  // map<string, int64> lbn2logical_object_id = 5;
  int lbn2logical_object_id_size() const;
  void clear_lbn2logical_object_id();
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int64 >&
      lbn2logical_object_id() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int64 >*
      mutable_lbn2logical_object_id();

  // map<string, .oneflow.ArgSignature> op_name2arg_signature = 9;
  int op_name2arg_signature_size() const;
  void clear_op_name2arg_signature();
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::ArgSignature >&
      op_name2arg_signature() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::ArgSignature >*
      mutable_op_name2arg_signature();

  // @@protoc_insertion_point(class_scope:oneflow.JobHelperConf)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      JobHelperConf_Tag2lbiRelationsEntry_DoNotUse,
      std::string, ::oneflow::LogicalBlobIdPairs,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
      0 > tag2lbi_relations_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      JobHelperConf_Tag2opNameRelationsEntry_DoNotUse,
      std::string, ::oneflow::OpNameRelations,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
      0 > tag2op_name_relations_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      JobHelperConf_Lbn2logicalBlobDescEntry_DoNotUse,
      std::string, ::oneflow::BlobDescProto,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
      0 > lbn2logical_blob_desc_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      JobHelperConf_Lbn2logicalObjectIdEntry_DoNotUse,
      std::string, ::PROTOBUF_NAMESPACE_ID::int64,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64,
      0 > lbn2logical_object_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      JobHelperConf_OpName2argSignatureEntry_DoNotUse,
      std::string, ::oneflow::ArgSignature,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
      0 > op_name2arg_signature_;
  friend struct ::TableStruct_oneflow_2fcore_2fjob_2fjob_2eproto;
};
// -------------------------------------------------------------------

class MergedLogicalChainIdGroup :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:oneflow.MergedLogicalChainIdGroup) */ {
 public:
  MergedLogicalChainIdGroup();
  virtual ~MergedLogicalChainIdGroup();

  MergedLogicalChainIdGroup(const MergedLogicalChainIdGroup& from);
  MergedLogicalChainIdGroup(MergedLogicalChainIdGroup&& from) noexcept
    : MergedLogicalChainIdGroup() {
    *this = ::std::move(from);
  }

  inline MergedLogicalChainIdGroup& operator=(const MergedLogicalChainIdGroup& from) {
    CopyFrom(from);
    return *this;
  }
  inline MergedLogicalChainIdGroup& operator=(MergedLogicalChainIdGroup&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MergedLogicalChainIdGroup& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MergedLogicalChainIdGroup* internal_default_instance() {
    return reinterpret_cast<const MergedLogicalChainIdGroup*>(
               &_MergedLogicalChainIdGroup_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    10;

  friend void swap(MergedLogicalChainIdGroup& a, MergedLogicalChainIdGroup& b) {
    a.Swap(&b);
  }
  inline void Swap(MergedLogicalChainIdGroup* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MergedLogicalChainIdGroup* New() const final {
    return CreateMaybeMessage<MergedLogicalChainIdGroup>(nullptr);
  }

  MergedLogicalChainIdGroup* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MergedLogicalChainIdGroup>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MergedLogicalChainIdGroup& from);
  void MergeFrom(const MergedLogicalChainIdGroup& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MergedLogicalChainIdGroup* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oneflow.MergedLogicalChainIdGroup";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_oneflow_2fcore_2fjob_2fjob_2eproto);
    return ::descriptor_table_oneflow_2fcore_2fjob_2fjob_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLogicalChainIdListFieldNumber = 1,
  };
  // repeated int64 logical_chain_id_list = 1;
  int logical_chain_id_list_size() const;
  void clear_logical_chain_id_list();
  ::PROTOBUF_NAMESPACE_ID::int64 logical_chain_id_list(int index) const;
  void set_logical_chain_id_list(int index, ::PROTOBUF_NAMESPACE_ID::int64 value);
  void add_logical_chain_id_list(::PROTOBUF_NAMESPACE_ID::int64 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
      logical_chain_id_list() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
      mutable_logical_chain_id_list();

  // @@protoc_insertion_point(class_scope:oneflow.MergedLogicalChainIdGroup)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 > logical_chain_id_list_;
  friend struct ::TableStruct_oneflow_2fcore_2fjob_2fjob_2eproto;
};
// -------------------------------------------------------------------

class Job_ModuleName2moduleConfEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Job_ModuleName2moduleConfEntry_DoNotUse, 
    std::string, ::oneflow::ModuleConf,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Job_ModuleName2moduleConfEntry_DoNotUse, 
    std::string, ::oneflow::ModuleConf,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  Job_ModuleName2moduleConfEntry_DoNotUse();
  Job_ModuleName2moduleConfEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const Job_ModuleName2moduleConfEntry_DoNotUse& other);
  static const Job_ModuleName2moduleConfEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Job_ModuleName2moduleConfEntry_DoNotUse*>(&_Job_ModuleName2moduleConfEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
#ifndef NDEBUG
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
       s->data(), s->size(), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "oneflow.Job.ModuleName2moduleConfEntry.key");
#endif
    return true;
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_oneflow_2fcore_2fjob_2fjob_2eproto);
    return ::descriptor_table_oneflow_2fcore_2fjob_2fjob_2eproto.file_level_metadata[11];
  }

  public:
};

// -------------------------------------------------------------------

class Job :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:oneflow.Job) */ {
 public:
  Job();
  virtual ~Job();

  Job(const Job& from);
  Job(Job&& from) noexcept
    : Job() {
    *this = ::std::move(from);
  }

  inline Job& operator=(const Job& from) {
    CopyFrom(from);
    return *this;
  }
  inline Job& operator=(Job&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Job& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Job* internal_default_instance() {
    return reinterpret_cast<const Job*>(
               &_Job_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    12;

  friend void swap(Job& a, Job& b) {
    a.Swap(&b);
  }
  inline void Swap(Job* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Job* New() const final {
    return CreateMaybeMessage<Job>(nullptr);
  }

  Job* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Job>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Job& from);
  void MergeFrom(const Job& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Job* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oneflow.Job";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_oneflow_2fcore_2fjob_2fjob_2eproto);
    return ::descriptor_table_oneflow_2fcore_2fjob_2fjob_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kModuleName2ModuleConfFieldNumber = 6,
    kLogicalChainGroupsFieldNumber = 7,
    kNetFieldNumber = 1,
    kPlacementFieldNumber = 2,
    kJobConfFieldNumber = 3,
    kJobParallelViewConfFieldNumber = 4,
    kHelperFieldNumber = 5,
  };
  // map<string, .oneflow.ModuleConf> module_name2module_conf = 6;
  int module_name2module_conf_size() const;
  void clear_module_name2module_conf();
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::ModuleConf >&
      module_name2module_conf() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::ModuleConf >*
      mutable_module_name2module_conf();

  // repeated .oneflow.MergedLogicalChainIdGroup logical_chain_groups = 7;
  int logical_chain_groups_size() const;
  void clear_logical_chain_groups();
  ::oneflow::MergedLogicalChainIdGroup* mutable_logical_chain_groups(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oneflow::MergedLogicalChainIdGroup >*
      mutable_logical_chain_groups();
  const ::oneflow::MergedLogicalChainIdGroup& logical_chain_groups(int index) const;
  ::oneflow::MergedLogicalChainIdGroup* add_logical_chain_groups();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oneflow::MergedLogicalChainIdGroup >&
      logical_chain_groups() const;

  // optional .oneflow.DLNetConf net = 1;
  bool has_net() const;
  void clear_net();
  const ::oneflow::DLNetConf& net() const;
  ::oneflow::DLNetConf* release_net();
  ::oneflow::DLNetConf* mutable_net();
  void set_allocated_net(::oneflow::DLNetConf* net);

  // optional .oneflow.Placement placement = 2;
  bool has_placement() const;
  void clear_placement();
  const ::oneflow::Placement& placement() const;
  ::oneflow::Placement* release_placement();
  ::oneflow::Placement* mutable_placement();
  void set_allocated_placement(::oneflow::Placement* placement);

  // required .oneflow.JobConfigProto job_conf = 3;
  bool has_job_conf() const;
  void clear_job_conf();
  const ::oneflow::JobConfigProto& job_conf() const;
  ::oneflow::JobConfigProto* release_job_conf();
  ::oneflow::JobConfigProto* mutable_job_conf();
  void set_allocated_job_conf(::oneflow::JobConfigProto* job_conf);

  // optional .oneflow.JobParallelViewConf job_parallel_view_conf = 4;
  bool has_job_parallel_view_conf() const;
  void clear_job_parallel_view_conf();
  const ::oneflow::JobParallelViewConf& job_parallel_view_conf() const;
  ::oneflow::JobParallelViewConf* release_job_parallel_view_conf();
  ::oneflow::JobParallelViewConf* mutable_job_parallel_view_conf();
  void set_allocated_job_parallel_view_conf(::oneflow::JobParallelViewConf* job_parallel_view_conf);

  // optional .oneflow.JobHelperConf helper = 5;
  bool has_helper() const;
  void clear_helper();
  const ::oneflow::JobHelperConf& helper() const;
  ::oneflow::JobHelperConf* release_helper();
  ::oneflow::JobHelperConf* mutable_helper();
  void set_allocated_helper(::oneflow::JobHelperConf* helper);

  // @@protoc_insertion_point(class_scope:oneflow.Job)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      Job_ModuleName2moduleConfEntry_DoNotUse,
      std::string, ::oneflow::ModuleConf,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
      0 > module_name2module_conf_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oneflow::MergedLogicalChainIdGroup > logical_chain_groups_;
  ::oneflow::DLNetConf* net_;
  ::oneflow::Placement* placement_;
  ::oneflow::JobConfigProto* job_conf_;
  ::oneflow::JobParallelViewConf* job_parallel_view_conf_;
  ::oneflow::JobHelperConf* helper_;
  friend struct ::TableStruct_oneflow_2fcore_2fjob_2fjob_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// JobParallelViewConf

// map<string, .oneflow.SbpSignature> op_name2sbp_signature_conf = 1;
inline int JobParallelViewConf::op_name2sbp_signature_conf_size() const {
  return op_name2sbp_signature_conf_.size();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::SbpSignature >&
JobParallelViewConf::op_name2sbp_signature_conf() const {
  // @@protoc_insertion_point(field_map:oneflow.JobParallelViewConf.op_name2sbp_signature_conf)
  return op_name2sbp_signature_conf_.GetMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::SbpSignature >*
JobParallelViewConf::mutable_op_name2sbp_signature_conf() {
  // @@protoc_insertion_point(field_mutable_map:oneflow.JobParallelViewConf.op_name2sbp_signature_conf)
  return op_name2sbp_signature_conf_.MutableMap();
}

// map<string, bool> op_name2is_local_parallel_view = 2;
inline int JobParallelViewConf::op_name2is_local_parallel_view_size() const {
  return op_name2is_local_parallel_view_.size();
}
inline void JobParallelViewConf::clear_op_name2is_local_parallel_view() {
  op_name2is_local_parallel_view_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, bool >&
JobParallelViewConf::op_name2is_local_parallel_view() const {
  // @@protoc_insertion_point(field_map:oneflow.JobParallelViewConf.op_name2is_local_parallel_view)
  return op_name2is_local_parallel_view_.GetMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, bool >*
JobParallelViewConf::mutable_op_name2is_local_parallel_view() {
  // @@protoc_insertion_point(field_mutable_map:oneflow.JobParallelViewConf.op_name2is_local_parallel_view)
  return op_name2is_local_parallel_view_.MutableMap();
}

// map<string, .oneflow.NdSbpSignature> op_name2nd_sbp_signature_conf = 3;
inline int JobParallelViewConf::op_name2nd_sbp_signature_conf_size() const {
  return op_name2nd_sbp_signature_conf_.size();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::NdSbpSignature >&
JobParallelViewConf::op_name2nd_sbp_signature_conf() const {
  // @@protoc_insertion_point(field_map:oneflow.JobParallelViewConf.op_name2nd_sbp_signature_conf)
  return op_name2nd_sbp_signature_conf_.GetMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::NdSbpSignature >*
JobParallelViewConf::mutable_op_name2nd_sbp_signature_conf() {
  // @@protoc_insertion_point(field_mutable_map:oneflow.JobParallelViewConf.op_name2nd_sbp_signature_conf)
  return op_name2nd_sbp_signature_conf_.MutableMap();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// JobHelperConf

// map<string, .oneflow.LogicalBlobIdPairs> tag2lbi_relations = 1;
inline int JobHelperConf::tag2lbi_relations_size() const {
  return tag2lbi_relations_.size();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::LogicalBlobIdPairs >&
JobHelperConf::tag2lbi_relations() const {
  // @@protoc_insertion_point(field_map:oneflow.JobHelperConf.tag2lbi_relations)
  return tag2lbi_relations_.GetMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::LogicalBlobIdPairs >*
JobHelperConf::mutable_tag2lbi_relations() {
  // @@protoc_insertion_point(field_mutable_map:oneflow.JobHelperConf.tag2lbi_relations)
  return tag2lbi_relations_.MutableMap();
}

// map<string, .oneflow.OpNameRelations> tag2op_name_relations = 2;
inline int JobHelperConf::tag2op_name_relations_size() const {
  return tag2op_name_relations_.size();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::OpNameRelations >&
JobHelperConf::tag2op_name_relations() const {
  // @@protoc_insertion_point(field_map:oneflow.JobHelperConf.tag2op_name_relations)
  return tag2op_name_relations_.GetMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::OpNameRelations >*
JobHelperConf::mutable_tag2op_name_relations() {
  // @@protoc_insertion_point(field_mutable_map:oneflow.JobHelperConf.tag2op_name_relations)
  return tag2op_name_relations_.MutableMap();
}

// map<string, .oneflow.BlobDescProto> lbn2logical_blob_desc = 4;
inline int JobHelperConf::lbn2logical_blob_desc_size() const {
  return lbn2logical_blob_desc_.size();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::BlobDescProto >&
JobHelperConf::lbn2logical_blob_desc() const {
  // @@protoc_insertion_point(field_map:oneflow.JobHelperConf.lbn2logical_blob_desc)
  return lbn2logical_blob_desc_.GetMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::BlobDescProto >*
JobHelperConf::mutable_lbn2logical_blob_desc() {
  // @@protoc_insertion_point(field_mutable_map:oneflow.JobHelperConf.lbn2logical_blob_desc)
  return lbn2logical_blob_desc_.MutableMap();
}

// map<string, int64> lbn2logical_object_id = 5;
inline int JobHelperConf::lbn2logical_object_id_size() const {
  return lbn2logical_object_id_.size();
}
inline void JobHelperConf::clear_lbn2logical_object_id() {
  lbn2logical_object_id_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int64 >&
JobHelperConf::lbn2logical_object_id() const {
  // @@protoc_insertion_point(field_map:oneflow.JobHelperConf.lbn2logical_object_id)
  return lbn2logical_object_id_.GetMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int64 >*
JobHelperConf::mutable_lbn2logical_object_id() {
  // @@protoc_insertion_point(field_mutable_map:oneflow.JobHelperConf.lbn2logical_object_id)
  return lbn2logical_object_id_.MutableMap();
}

// map<string, .oneflow.ArgSignature> op_name2arg_signature = 9;
inline int JobHelperConf::op_name2arg_signature_size() const {
  return op_name2arg_signature_.size();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::ArgSignature >&
JobHelperConf::op_name2arg_signature() const {
  // @@protoc_insertion_point(field_map:oneflow.JobHelperConf.op_name2arg_signature)
  return op_name2arg_signature_.GetMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::ArgSignature >*
JobHelperConf::mutable_op_name2arg_signature() {
  // @@protoc_insertion_point(field_mutable_map:oneflow.JobHelperConf.op_name2arg_signature)
  return op_name2arg_signature_.MutableMap();
}

// -------------------------------------------------------------------

// MergedLogicalChainIdGroup

// repeated int64 logical_chain_id_list = 1;
inline int MergedLogicalChainIdGroup::logical_chain_id_list_size() const {
  return logical_chain_id_list_.size();
}
inline void MergedLogicalChainIdGroup::clear_logical_chain_id_list() {
  logical_chain_id_list_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MergedLogicalChainIdGroup::logical_chain_id_list(int index) const {
  // @@protoc_insertion_point(field_get:oneflow.MergedLogicalChainIdGroup.logical_chain_id_list)
  return logical_chain_id_list_.Get(index);
}
inline void MergedLogicalChainIdGroup::set_logical_chain_id_list(int index, ::PROTOBUF_NAMESPACE_ID::int64 value) {
  logical_chain_id_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:oneflow.MergedLogicalChainIdGroup.logical_chain_id_list)
}
inline void MergedLogicalChainIdGroup::add_logical_chain_id_list(::PROTOBUF_NAMESPACE_ID::int64 value) {
  logical_chain_id_list_.Add(value);
  // @@protoc_insertion_point(field_add:oneflow.MergedLogicalChainIdGroup.logical_chain_id_list)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
MergedLogicalChainIdGroup::logical_chain_id_list() const {
  // @@protoc_insertion_point(field_list:oneflow.MergedLogicalChainIdGroup.logical_chain_id_list)
  return logical_chain_id_list_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
MergedLogicalChainIdGroup::mutable_logical_chain_id_list() {
  // @@protoc_insertion_point(field_mutable_list:oneflow.MergedLogicalChainIdGroup.logical_chain_id_list)
  return &logical_chain_id_list_;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// Job

// optional .oneflow.DLNetConf net = 1;
inline bool Job::has_net() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline const ::oneflow::DLNetConf& Job::net() const {
  const ::oneflow::DLNetConf* p = net_;
  // @@protoc_insertion_point(field_get:oneflow.Job.net)
  return p != nullptr ? *p : *reinterpret_cast<const ::oneflow::DLNetConf*>(
      &::oneflow::_DLNetConf_default_instance_);
}
inline ::oneflow::DLNetConf* Job::release_net() {
  // @@protoc_insertion_point(field_release:oneflow.Job.net)
  _has_bits_[0] &= ~0x00000001u;
  ::oneflow::DLNetConf* temp = net_;
  net_ = nullptr;
  return temp;
}
inline ::oneflow::DLNetConf* Job::mutable_net() {
  _has_bits_[0] |= 0x00000001u;
  if (net_ == nullptr) {
    auto* p = CreateMaybeMessage<::oneflow::DLNetConf>(GetArenaNoVirtual());
    net_ = p;
  }
  // @@protoc_insertion_point(field_mutable:oneflow.Job.net)
  return net_;
}
inline void Job::set_allocated_net(::oneflow::DLNetConf* net) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(net_);
  }
  if (net) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      net = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, net, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  net_ = net;
  // @@protoc_insertion_point(field_set_allocated:oneflow.Job.net)
}

// optional .oneflow.Placement placement = 2;
inline bool Job::has_placement() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline const ::oneflow::Placement& Job::placement() const {
  const ::oneflow::Placement* p = placement_;
  // @@protoc_insertion_point(field_get:oneflow.Job.placement)
  return p != nullptr ? *p : *reinterpret_cast<const ::oneflow::Placement*>(
      &::oneflow::_Placement_default_instance_);
}
inline ::oneflow::Placement* Job::release_placement() {
  // @@protoc_insertion_point(field_release:oneflow.Job.placement)
  _has_bits_[0] &= ~0x00000002u;
  ::oneflow::Placement* temp = placement_;
  placement_ = nullptr;
  return temp;
}
inline ::oneflow::Placement* Job::mutable_placement() {
  _has_bits_[0] |= 0x00000002u;
  if (placement_ == nullptr) {
    auto* p = CreateMaybeMessage<::oneflow::Placement>(GetArenaNoVirtual());
    placement_ = p;
  }
  // @@protoc_insertion_point(field_mutable:oneflow.Job.placement)
  return placement_;
}
inline void Job::set_allocated_placement(::oneflow::Placement* placement) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(placement_);
  }
  if (placement) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      placement = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, placement, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  placement_ = placement;
  // @@protoc_insertion_point(field_set_allocated:oneflow.Job.placement)
}

// required .oneflow.JobConfigProto job_conf = 3;
inline bool Job::has_job_conf() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline const ::oneflow::JobConfigProto& Job::job_conf() const {
  const ::oneflow::JobConfigProto* p = job_conf_;
  // @@protoc_insertion_point(field_get:oneflow.Job.job_conf)
  return p != nullptr ? *p : *reinterpret_cast<const ::oneflow::JobConfigProto*>(
      &::oneflow::_JobConfigProto_default_instance_);
}
inline ::oneflow::JobConfigProto* Job::release_job_conf() {
  // @@protoc_insertion_point(field_release:oneflow.Job.job_conf)
  _has_bits_[0] &= ~0x00000004u;
  ::oneflow::JobConfigProto* temp = job_conf_;
  job_conf_ = nullptr;
  return temp;
}
inline ::oneflow::JobConfigProto* Job::mutable_job_conf() {
  _has_bits_[0] |= 0x00000004u;
  if (job_conf_ == nullptr) {
    auto* p = CreateMaybeMessage<::oneflow::JobConfigProto>(GetArenaNoVirtual());
    job_conf_ = p;
  }
  // @@protoc_insertion_point(field_mutable:oneflow.Job.job_conf)
  return job_conf_;
}
inline void Job::set_allocated_job_conf(::oneflow::JobConfigProto* job_conf) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(job_conf_);
  }
  if (job_conf) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      job_conf = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, job_conf, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  job_conf_ = job_conf;
  // @@protoc_insertion_point(field_set_allocated:oneflow.Job.job_conf)
}

// optional .oneflow.JobParallelViewConf job_parallel_view_conf = 4;
inline bool Job::has_job_parallel_view_conf() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Job::clear_job_parallel_view_conf() {
  if (job_parallel_view_conf_ != nullptr) job_parallel_view_conf_->Clear();
  _has_bits_[0] &= ~0x00000008u;
}
inline const ::oneflow::JobParallelViewConf& Job::job_parallel_view_conf() const {
  const ::oneflow::JobParallelViewConf* p = job_parallel_view_conf_;
  // @@protoc_insertion_point(field_get:oneflow.Job.job_parallel_view_conf)
  return p != nullptr ? *p : *reinterpret_cast<const ::oneflow::JobParallelViewConf*>(
      &::oneflow::_JobParallelViewConf_default_instance_);
}
inline ::oneflow::JobParallelViewConf* Job::release_job_parallel_view_conf() {
  // @@protoc_insertion_point(field_release:oneflow.Job.job_parallel_view_conf)
  _has_bits_[0] &= ~0x00000008u;
  ::oneflow::JobParallelViewConf* temp = job_parallel_view_conf_;
  job_parallel_view_conf_ = nullptr;
  return temp;
}
inline ::oneflow::JobParallelViewConf* Job::mutable_job_parallel_view_conf() {
  _has_bits_[0] |= 0x00000008u;
  if (job_parallel_view_conf_ == nullptr) {
    auto* p = CreateMaybeMessage<::oneflow::JobParallelViewConf>(GetArenaNoVirtual());
    job_parallel_view_conf_ = p;
  }
  // @@protoc_insertion_point(field_mutable:oneflow.Job.job_parallel_view_conf)
  return job_parallel_view_conf_;
}
inline void Job::set_allocated_job_parallel_view_conf(::oneflow::JobParallelViewConf* job_parallel_view_conf) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete job_parallel_view_conf_;
  }
  if (job_parallel_view_conf) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      job_parallel_view_conf = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, job_parallel_view_conf, submessage_arena);
    }
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  job_parallel_view_conf_ = job_parallel_view_conf;
  // @@protoc_insertion_point(field_set_allocated:oneflow.Job.job_parallel_view_conf)
}

// optional .oneflow.JobHelperConf helper = 5;
inline bool Job::has_helper() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Job::clear_helper() {
  if (helper_ != nullptr) helper_->Clear();
  _has_bits_[0] &= ~0x00000010u;
}
inline const ::oneflow::JobHelperConf& Job::helper() const {
  const ::oneflow::JobHelperConf* p = helper_;
  // @@protoc_insertion_point(field_get:oneflow.Job.helper)
  return p != nullptr ? *p : *reinterpret_cast<const ::oneflow::JobHelperConf*>(
      &::oneflow::_JobHelperConf_default_instance_);
}
inline ::oneflow::JobHelperConf* Job::release_helper() {
  // @@protoc_insertion_point(field_release:oneflow.Job.helper)
  _has_bits_[0] &= ~0x00000010u;
  ::oneflow::JobHelperConf* temp = helper_;
  helper_ = nullptr;
  return temp;
}
inline ::oneflow::JobHelperConf* Job::mutable_helper() {
  _has_bits_[0] |= 0x00000010u;
  if (helper_ == nullptr) {
    auto* p = CreateMaybeMessage<::oneflow::JobHelperConf>(GetArenaNoVirtual());
    helper_ = p;
  }
  // @@protoc_insertion_point(field_mutable:oneflow.Job.helper)
  return helper_;
}
inline void Job::set_allocated_helper(::oneflow::JobHelperConf* helper) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete helper_;
  }
  if (helper) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      helper = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, helper, submessage_arena);
    }
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  helper_ = helper;
  // @@protoc_insertion_point(field_set_allocated:oneflow.Job.helper)
}

// map<string, .oneflow.ModuleConf> module_name2module_conf = 6;
inline int Job::module_name2module_conf_size() const {
  return module_name2module_conf_.size();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::ModuleConf >&
Job::module_name2module_conf() const {
  // @@protoc_insertion_point(field_map:oneflow.Job.module_name2module_conf)
  return module_name2module_conf_.GetMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::oneflow::ModuleConf >*
Job::mutable_module_name2module_conf() {
  // @@protoc_insertion_point(field_mutable_map:oneflow.Job.module_name2module_conf)
  return module_name2module_conf_.MutableMap();
}

// repeated .oneflow.MergedLogicalChainIdGroup logical_chain_groups = 7;
inline int Job::logical_chain_groups_size() const {
  return logical_chain_groups_.size();
}
inline void Job::clear_logical_chain_groups() {
  logical_chain_groups_.Clear();
}
inline ::oneflow::MergedLogicalChainIdGroup* Job::mutable_logical_chain_groups(int index) {
  // @@protoc_insertion_point(field_mutable:oneflow.Job.logical_chain_groups)
  return logical_chain_groups_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oneflow::MergedLogicalChainIdGroup >*
Job::mutable_logical_chain_groups() {
  // @@protoc_insertion_point(field_mutable_list:oneflow.Job.logical_chain_groups)
  return &logical_chain_groups_;
}
inline const ::oneflow::MergedLogicalChainIdGroup& Job::logical_chain_groups(int index) const {
  // @@protoc_insertion_point(field_get:oneflow.Job.logical_chain_groups)
  return logical_chain_groups_.Get(index);
}
inline ::oneflow::MergedLogicalChainIdGroup* Job::add_logical_chain_groups() {
  // @@protoc_insertion_point(field_add:oneflow.Job.logical_chain_groups)
  return logical_chain_groups_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::oneflow::MergedLogicalChainIdGroup >&
Job::logical_chain_groups() const {
  // @@protoc_insertion_point(field_list:oneflow.Job.logical_chain_groups)
  return logical_chain_groups_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace oneflow

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_oneflow_2fcore_2fjob_2fjob_2eproto
