
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-05T10:07:22+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c9e18f22f46ff461012cfe4bbc115ea9916d8e68",
 "version": "1.1.0b0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
