class Data:
    SYNC = b"S"
    SYNC_LENGTH = len(SYNC)
    REQUEST_LENGHT = 4
    BUFFER_SIZE = 8192
    SEND_INT = 2
    SEND_INT_LONG = 8
    CLOSE_CONNECTION = "CCON"
    SEND_AUTHENTICATION = "SAUT"
    RECV_AUTHENTICATION = "RAUT"
    SEND_FILE = "SFIL"
    RECEIVE_FILE = "RFIL"
