# coding: utf-8

"""
    Data Modelling Storage Service

    API for basic data modelling interaction  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import dmss_api
from dmss_api.model.basic_entity import BasicEntity
from dmss_api import configuration


class TestBasicEntity(unittest.TestCase):
    """BasicEntity unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
