
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-30T09:55:48+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5c646812b5339add87e8d3f141593ec571179092",
 "version": "0.0.6.dev20230104"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
