# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bastionlab_polars.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x62\x61stionlab_polars.proto\x12\x11\x62\x61stionlab_polars\"&\n\x10ReferenceRequest\x12\x12\n\nidentifier\x18\x01 \x01(\t\"7\n\x11ReferenceResponse\x12\x12\n\nidentifier\x18\x01 \x01(\t\x12\x0e\n\x06header\x18\x02 \x01(\t\"C\n\rReferenceList\x12\x32\n\x04list\x18\x01 \x03(\x0b\x32$.bastionlab_polars.ReferenceResponse\";\n\tSendChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0e\n\x06policy\x18\x02 \x01(\t\x12\x10\n\x08metadata\x18\x03 \x01(\t\"J\n\nFetchChunk\x12\x0e\n\x04\x64\x61ta\x18\x01 \x01(\x0cH\x00\x12\x11\n\x07pending\x18\x02 \x01(\tH\x00\x12\x11\n\x07warning\x18\x03 \x01(\tH\x00\x42\x06\n\x04\x62ody\"\x1f\n\x05Query\x12\x16\n\x0e\x63omposite_plan\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xec\x04\n\rPolarsService\x12W\n\rSendDataFrame\x12\x1c.bastionlab_polars.SendChunk\x1a$.bastionlab_polars.ReferenceResponse\"\x00(\x01\x12L\n\x08RunQuery\x12\x18.bastionlab_polars.Query\x1a$.bastionlab_polars.ReferenceResponse\"\x00\x12X\n\x0e\x46\x65tchDataFrame\x12#.bastionlab_polars.ReferenceRequest\x1a\x1d.bastionlab_polars.FetchChunk\"\x00\x30\x01\x12N\n\x0eListDataFrames\x12\x18.bastionlab_polars.Empty\x1a .bastionlab_polars.ReferenceList\"\x00\x12\x61\n\x12GetDataFrameHeader\x12#.bastionlab_polars.ReferenceRequest\x1a$.bastionlab_polars.ReferenceResponse\"\x00\x12S\n\x10PersistDataFrame\x12#.bastionlab_polars.ReferenceRequest\x1a\x18.bastionlab_polars.Empty\"\x00\x12R\n\x0f\x44\x65leteDataFrame\x12#.bastionlab_polars.ReferenceRequest\x1a\x18.bastionlab_polars.Empty\"\x00\x62\x06proto3')



_REFERENCEREQUEST = DESCRIPTOR.message_types_by_name['ReferenceRequest']
_REFERENCERESPONSE = DESCRIPTOR.message_types_by_name['ReferenceResponse']
_REFERENCELIST = DESCRIPTOR.message_types_by_name['ReferenceList']
_SENDCHUNK = DESCRIPTOR.message_types_by_name['SendChunk']
_FETCHCHUNK = DESCRIPTOR.message_types_by_name['FetchChunk']
_QUERY = DESCRIPTOR.message_types_by_name['Query']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
ReferenceRequest = _reflection.GeneratedProtocolMessageType('ReferenceRequest', (_message.Message,), {
  'DESCRIPTOR' : _REFERENCEREQUEST,
  '__module__' : 'bastionlab_polars_pb2'
  # @@protoc_insertion_point(class_scope:bastionlab_polars.ReferenceRequest)
  })
_sym_db.RegisterMessage(ReferenceRequest)

ReferenceResponse = _reflection.GeneratedProtocolMessageType('ReferenceResponse', (_message.Message,), {
  'DESCRIPTOR' : _REFERENCERESPONSE,
  '__module__' : 'bastionlab_polars_pb2'
  # @@protoc_insertion_point(class_scope:bastionlab_polars.ReferenceResponse)
  })
_sym_db.RegisterMessage(ReferenceResponse)

ReferenceList = _reflection.GeneratedProtocolMessageType('ReferenceList', (_message.Message,), {
  'DESCRIPTOR' : _REFERENCELIST,
  '__module__' : 'bastionlab_polars_pb2'
  # @@protoc_insertion_point(class_scope:bastionlab_polars.ReferenceList)
  })
_sym_db.RegisterMessage(ReferenceList)

SendChunk = _reflection.GeneratedProtocolMessageType('SendChunk', (_message.Message,), {
  'DESCRIPTOR' : _SENDCHUNK,
  '__module__' : 'bastionlab_polars_pb2'
  # @@protoc_insertion_point(class_scope:bastionlab_polars.SendChunk)
  })
_sym_db.RegisterMessage(SendChunk)

FetchChunk = _reflection.GeneratedProtocolMessageType('FetchChunk', (_message.Message,), {
  'DESCRIPTOR' : _FETCHCHUNK,
  '__module__' : 'bastionlab_polars_pb2'
  # @@protoc_insertion_point(class_scope:bastionlab_polars.FetchChunk)
  })
_sym_db.RegisterMessage(FetchChunk)

Query = _reflection.GeneratedProtocolMessageType('Query', (_message.Message,), {
  'DESCRIPTOR' : _QUERY,
  '__module__' : 'bastionlab_polars_pb2'
  # @@protoc_insertion_point(class_scope:bastionlab_polars.Query)
  })
_sym_db.RegisterMessage(Query)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'bastionlab_polars_pb2'
  # @@protoc_insertion_point(class_scope:bastionlab_polars.Empty)
  })
_sym_db.RegisterMessage(Empty)

_POLARSSERVICE = DESCRIPTOR.services_by_name['PolarsService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REFERENCEREQUEST._serialized_start=46
  _REFERENCEREQUEST._serialized_end=84
  _REFERENCERESPONSE._serialized_start=86
  _REFERENCERESPONSE._serialized_end=141
  _REFERENCELIST._serialized_start=143
  _REFERENCELIST._serialized_end=210
  _SENDCHUNK._serialized_start=212
  _SENDCHUNK._serialized_end=271
  _FETCHCHUNK._serialized_start=273
  _FETCHCHUNK._serialized_end=347
  _QUERY._serialized_start=349
  _QUERY._serialized_end=380
  _EMPTY._serialized_start=382
  _EMPTY._serialized_end=389
  _POLARSSERVICE._serialized_start=392
  _POLARSSERVICE._serialized_end=1012
# @@protoc_insertion_point(module_scope)
