# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oneflow/core/job/sbp_parallel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='oneflow/core/job/sbp_parallel.proto',
  package='oneflow',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n#oneflow/core/job/sbp_parallel.proto\x12\x07oneflow\"\x1d\n\rSplitParallel\x12\x0c\n\x04\x61xis\x18\x01 \x02(\x03\"\x13\n\x11\x42roadcastParallel\"\x14\n\x12PartialSumParallel\"\xc7\x01\n\x0bSbpParallel\x12\x30\n\x0esplit_parallel\x18\x01 \x01(\x0b\x32\x16.oneflow.SplitParallelH\x00\x12\x38\n\x12\x62roadcast_parallel\x18\x02 \x01(\x0b\x32\x1a.oneflow.BroadcastParallelH\x00\x12;\n\x14partial_sum_parallel\x18\x03 \x01(\x0b\x32\x1b.oneflow.PartialSumParallelH\x00\x42\x0f\n\rparallel_type\"\xad\x01\n\x0cSbpSignature\x12L\n\x15\x62n_in_op2sbp_parallel\x18\x01 \x03(\x0b\x32-.oneflow.SbpSignature.BnInOp2sbpParallelEntry\x1aO\n\x17\x42nInOp2sbpParallelEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.oneflow.SbpParallel:\x02\x38\x01\"3\n\x05NdSbp\x12*\n\x0csbp_parallel\x18\x01 \x03(\x0b\x32\x14.oneflow.SbpParallel\"\x99\x01\n\x0eNdSbpSignature\x12\x42\n\x0f\x62n_in_op2nd_sbp\x18\x01 \x03(\x0b\x32).oneflow.NdSbpSignature.BnInOp2ndSbpEntry\x1a\x43\n\x11\x42nInOp2ndSbpEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.oneflow.NdSbp:\x02\x38\x01\"@\n\x10SbpSignatureList\x12,\n\rsbp_signature\x18\x01 \x03(\x0b\x32\x15.oneflow.SbpSignature')
)




_SPLITPARALLEL = _descriptor.Descriptor(
  name='SplitParallel',
  full_name='oneflow.SplitParallel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='axis', full_name='oneflow.SplitParallel.axis', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=77,
)


_BROADCASTPARALLEL = _descriptor.Descriptor(
  name='BroadcastParallel',
  full_name='oneflow.BroadcastParallel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=98,
)


_PARTIALSUMPARALLEL = _descriptor.Descriptor(
  name='PartialSumParallel',
  full_name='oneflow.PartialSumParallel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=120,
)


_SBPPARALLEL = _descriptor.Descriptor(
  name='SbpParallel',
  full_name='oneflow.SbpParallel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='split_parallel', full_name='oneflow.SbpParallel.split_parallel', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='broadcast_parallel', full_name='oneflow.SbpParallel.broadcast_parallel', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='partial_sum_parallel', full_name='oneflow.SbpParallel.partial_sum_parallel', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='parallel_type', full_name='oneflow.SbpParallel.parallel_type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=123,
  serialized_end=322,
)


_SBPSIGNATURE_BNINOP2SBPPARALLELENTRY = _descriptor.Descriptor(
  name='BnInOp2sbpParallelEntry',
  full_name='oneflow.SbpSignature.BnInOp2sbpParallelEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='oneflow.SbpSignature.BnInOp2sbpParallelEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='oneflow.SbpSignature.BnInOp2sbpParallelEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=419,
  serialized_end=498,
)

_SBPSIGNATURE = _descriptor.Descriptor(
  name='SbpSignature',
  full_name='oneflow.SbpSignature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bn_in_op2sbp_parallel', full_name='oneflow.SbpSignature.bn_in_op2sbp_parallel', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SBPSIGNATURE_BNINOP2SBPPARALLELENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=498,
)


_NDSBP = _descriptor.Descriptor(
  name='NdSbp',
  full_name='oneflow.NdSbp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sbp_parallel', full_name='oneflow.NdSbp.sbp_parallel', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=500,
  serialized_end=551,
)


_NDSBPSIGNATURE_BNINOP2NDSBPENTRY = _descriptor.Descriptor(
  name='BnInOp2ndSbpEntry',
  full_name='oneflow.NdSbpSignature.BnInOp2ndSbpEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='oneflow.NdSbpSignature.BnInOp2ndSbpEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='oneflow.NdSbpSignature.BnInOp2ndSbpEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=640,
  serialized_end=707,
)

_NDSBPSIGNATURE = _descriptor.Descriptor(
  name='NdSbpSignature',
  full_name='oneflow.NdSbpSignature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bn_in_op2nd_sbp', full_name='oneflow.NdSbpSignature.bn_in_op2nd_sbp', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_NDSBPSIGNATURE_BNINOP2NDSBPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=554,
  serialized_end=707,
)


_SBPSIGNATURELIST = _descriptor.Descriptor(
  name='SbpSignatureList',
  full_name='oneflow.SbpSignatureList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sbp_signature', full_name='oneflow.SbpSignatureList.sbp_signature', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=709,
  serialized_end=773,
)

_SBPPARALLEL.fields_by_name['split_parallel'].message_type = _SPLITPARALLEL
_SBPPARALLEL.fields_by_name['broadcast_parallel'].message_type = _BROADCASTPARALLEL
_SBPPARALLEL.fields_by_name['partial_sum_parallel'].message_type = _PARTIALSUMPARALLEL
_SBPPARALLEL.oneofs_by_name['parallel_type'].fields.append(
  _SBPPARALLEL.fields_by_name['split_parallel'])
_SBPPARALLEL.fields_by_name['split_parallel'].containing_oneof = _SBPPARALLEL.oneofs_by_name['parallel_type']
_SBPPARALLEL.oneofs_by_name['parallel_type'].fields.append(
  _SBPPARALLEL.fields_by_name['broadcast_parallel'])
_SBPPARALLEL.fields_by_name['broadcast_parallel'].containing_oneof = _SBPPARALLEL.oneofs_by_name['parallel_type']
_SBPPARALLEL.oneofs_by_name['parallel_type'].fields.append(
  _SBPPARALLEL.fields_by_name['partial_sum_parallel'])
_SBPPARALLEL.fields_by_name['partial_sum_parallel'].containing_oneof = _SBPPARALLEL.oneofs_by_name['parallel_type']
_SBPSIGNATURE_BNINOP2SBPPARALLELENTRY.fields_by_name['value'].message_type = _SBPPARALLEL
_SBPSIGNATURE_BNINOP2SBPPARALLELENTRY.containing_type = _SBPSIGNATURE
_SBPSIGNATURE.fields_by_name['bn_in_op2sbp_parallel'].message_type = _SBPSIGNATURE_BNINOP2SBPPARALLELENTRY
_NDSBP.fields_by_name['sbp_parallel'].message_type = _SBPPARALLEL
_NDSBPSIGNATURE_BNINOP2NDSBPENTRY.fields_by_name['value'].message_type = _NDSBP
_NDSBPSIGNATURE_BNINOP2NDSBPENTRY.containing_type = _NDSBPSIGNATURE
_NDSBPSIGNATURE.fields_by_name['bn_in_op2nd_sbp'].message_type = _NDSBPSIGNATURE_BNINOP2NDSBPENTRY
_SBPSIGNATURELIST.fields_by_name['sbp_signature'].message_type = _SBPSIGNATURE
DESCRIPTOR.message_types_by_name['SplitParallel'] = _SPLITPARALLEL
DESCRIPTOR.message_types_by_name['BroadcastParallel'] = _BROADCASTPARALLEL
DESCRIPTOR.message_types_by_name['PartialSumParallel'] = _PARTIALSUMPARALLEL
DESCRIPTOR.message_types_by_name['SbpParallel'] = _SBPPARALLEL
DESCRIPTOR.message_types_by_name['SbpSignature'] = _SBPSIGNATURE
DESCRIPTOR.message_types_by_name['NdSbp'] = _NDSBP
DESCRIPTOR.message_types_by_name['NdSbpSignature'] = _NDSBPSIGNATURE
DESCRIPTOR.message_types_by_name['SbpSignatureList'] = _SBPSIGNATURELIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SplitParallel = _reflection.GeneratedProtocolMessageType('SplitParallel', (_message.Message,), {
  'DESCRIPTOR' : _SPLITPARALLEL,
  '__module__' : 'oneflow.core.job.sbp_parallel_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.SplitParallel)
  })
_sym_db.RegisterMessage(SplitParallel)

BroadcastParallel = _reflection.GeneratedProtocolMessageType('BroadcastParallel', (_message.Message,), {
  'DESCRIPTOR' : _BROADCASTPARALLEL,
  '__module__' : 'oneflow.core.job.sbp_parallel_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.BroadcastParallel)
  })
_sym_db.RegisterMessage(BroadcastParallel)

PartialSumParallel = _reflection.GeneratedProtocolMessageType('PartialSumParallel', (_message.Message,), {
  'DESCRIPTOR' : _PARTIALSUMPARALLEL,
  '__module__' : 'oneflow.core.job.sbp_parallel_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.PartialSumParallel)
  })
_sym_db.RegisterMessage(PartialSumParallel)

SbpParallel = _reflection.GeneratedProtocolMessageType('SbpParallel', (_message.Message,), {
  'DESCRIPTOR' : _SBPPARALLEL,
  '__module__' : 'oneflow.core.job.sbp_parallel_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.SbpParallel)
  })
_sym_db.RegisterMessage(SbpParallel)

SbpSignature = _reflection.GeneratedProtocolMessageType('SbpSignature', (_message.Message,), {

  'BnInOp2sbpParallelEntry' : _reflection.GeneratedProtocolMessageType('BnInOp2sbpParallelEntry', (_message.Message,), {
    'DESCRIPTOR' : _SBPSIGNATURE_BNINOP2SBPPARALLELENTRY,
    '__module__' : 'oneflow.core.job.sbp_parallel_pb2'
    # @@protoc_insertion_point(class_scope:oneflow.SbpSignature.BnInOp2sbpParallelEntry)
    })
  ,
  'DESCRIPTOR' : _SBPSIGNATURE,
  '__module__' : 'oneflow.core.job.sbp_parallel_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.SbpSignature)
  })
_sym_db.RegisterMessage(SbpSignature)
_sym_db.RegisterMessage(SbpSignature.BnInOp2sbpParallelEntry)

NdSbp = _reflection.GeneratedProtocolMessageType('NdSbp', (_message.Message,), {
  'DESCRIPTOR' : _NDSBP,
  '__module__' : 'oneflow.core.job.sbp_parallel_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.NdSbp)
  })
_sym_db.RegisterMessage(NdSbp)

NdSbpSignature = _reflection.GeneratedProtocolMessageType('NdSbpSignature', (_message.Message,), {

  'BnInOp2ndSbpEntry' : _reflection.GeneratedProtocolMessageType('BnInOp2ndSbpEntry', (_message.Message,), {
    'DESCRIPTOR' : _NDSBPSIGNATURE_BNINOP2NDSBPENTRY,
    '__module__' : 'oneflow.core.job.sbp_parallel_pb2'
    # @@protoc_insertion_point(class_scope:oneflow.NdSbpSignature.BnInOp2ndSbpEntry)
    })
  ,
  'DESCRIPTOR' : _NDSBPSIGNATURE,
  '__module__' : 'oneflow.core.job.sbp_parallel_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.NdSbpSignature)
  })
_sym_db.RegisterMessage(NdSbpSignature)
_sym_db.RegisterMessage(NdSbpSignature.BnInOp2ndSbpEntry)

SbpSignatureList = _reflection.GeneratedProtocolMessageType('SbpSignatureList', (_message.Message,), {
  'DESCRIPTOR' : _SBPSIGNATURELIST,
  '__module__' : 'oneflow.core.job.sbp_parallel_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.SbpSignatureList)
  })
_sym_db.RegisterMessage(SbpSignatureList)


_SBPSIGNATURE_BNINOP2SBPPARALLELENTRY._options = None
_NDSBPSIGNATURE_BNINOP2NDSBPENTRY._options = None
# @@protoc_insertion_point(module_scope)
