# Generated by Django 4.0.3 on 2022-03-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_developer_alter_game_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='english_patched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='english_patched_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='hack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='hack_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
