# Generated by Django 4.0.3 on 2022-04-01 02:15

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='marquee',
            field=models.ImageField(blank=True, null=True, upload_to=games.models.get_marquee_upload_path),
        ),
        migrations.AlterField(
            model_name='game',
            name='region',
            field=models.CharField(blank=True, choices=[('US', 'USA'), ('EU', 'Europe'), ('JP', 'Japan'), ('X', 'Unknown')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=games.models.get_screenshot_upload_path),
        ),
    ]
