# Generated by Django 4.0.4 on 2022-04-27 17:41

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('games', '0017_game_featured_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='featured',
        ),
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
