# Generated by Django 4.1.3 on 2023-01-05 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'games',
            '0020_developer_uuid_game_uuid_gamecollection_uuid_and_more',
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='finished_on',
        ),
        migrations.RemoveField(
            model_name='game',
            name='started_on',
        ),
    ]
