// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/job/parallel_signature.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_oneflow_2fcore_2fjob_2fparallel_5fsignature_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_oneflow_2fcore_2fjob_2fparallel_5fsignature_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_oneflow_2fcore_2fjob_2fparallel_5fsignature_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_oneflow_2fcore_2fjob_2fparallel_5fsignature_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_oneflow_2fcore_2fjob_2fparallel_5fsignature_2eproto;
namespace oneflow {
class ParallelSignature;
class ParallelSignatureDefaultTypeInternal;
extern ParallelSignatureDefaultTypeInternal _ParallelSignature_default_instance_;
class ParallelSignature_BnInOp2parallelDescSymbolIdEntry_DoNotUse;
class ParallelSignature_BnInOp2parallelDescSymbolIdEntry_DoNotUseDefaultTypeInternal;
extern ParallelSignature_BnInOp2parallelDescSymbolIdEntry_DoNotUseDefaultTypeInternal _ParallelSignature_BnInOp2parallelDescSymbolIdEntry_DoNotUse_default_instance_;
}  // namespace oneflow
PROTOBUF_NAMESPACE_OPEN
template<> ::oneflow::ParallelSignature* Arena::CreateMaybeMessage<::oneflow::ParallelSignature>(Arena*);
template<> ::oneflow::ParallelSignature_BnInOp2parallelDescSymbolIdEntry_DoNotUse* Arena::CreateMaybeMessage<::oneflow::ParallelSignature_BnInOp2parallelDescSymbolIdEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace oneflow {

// ===================================================================

class ParallelSignature_BnInOp2parallelDescSymbolIdEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<ParallelSignature_BnInOp2parallelDescSymbolIdEntry_DoNotUse, 
    std::string, ::PROTOBUF_NAMESPACE_ID::int64,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64,
    0 > {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<ParallelSignature_BnInOp2parallelDescSymbolIdEntry_DoNotUse, 
    std::string, ::PROTOBUF_NAMESPACE_ID::int64,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64,
    0 > SuperType;
  ParallelSignature_BnInOp2parallelDescSymbolIdEntry_DoNotUse();
  ParallelSignature_BnInOp2parallelDescSymbolIdEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const ParallelSignature_BnInOp2parallelDescSymbolIdEntry_DoNotUse& other);
  static const ParallelSignature_BnInOp2parallelDescSymbolIdEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const ParallelSignature_BnInOp2parallelDescSymbolIdEntry_DoNotUse*>(&_ParallelSignature_BnInOp2parallelDescSymbolIdEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
#ifndef NDEBUG
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
       s->data(), s->size(), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "oneflow.ParallelSignature.BnInOp2parallelDescSymbolIdEntry.key");
#endif
    return true;
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_oneflow_2fcore_2fjob_2fparallel_5fsignature_2eproto);
    return ::descriptor_table_oneflow_2fcore_2fjob_2fparallel_5fsignature_2eproto.file_level_metadata[0];
  }

  public:
};

// -------------------------------------------------------------------

class ParallelSignature :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:oneflow.ParallelSignature) */ {
 public:
  ParallelSignature();
  virtual ~ParallelSignature();

  ParallelSignature(const ParallelSignature& from);
  ParallelSignature(ParallelSignature&& from) noexcept
    : ParallelSignature() {
    *this = ::std::move(from);
  }

  inline ParallelSignature& operator=(const ParallelSignature& from) {
    CopyFrom(from);
    return *this;
  }
  inline ParallelSignature& operator=(ParallelSignature&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ParallelSignature& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ParallelSignature* internal_default_instance() {
    return reinterpret_cast<const ParallelSignature*>(
               &_ParallelSignature_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ParallelSignature& a, ParallelSignature& b) {
    a.Swap(&b);
  }
  inline void Swap(ParallelSignature* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ParallelSignature* New() const final {
    return CreateMaybeMessage<ParallelSignature>(nullptr);
  }

  ParallelSignature* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ParallelSignature>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ParallelSignature& from);
  void MergeFrom(const ParallelSignature& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ParallelSignature* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "oneflow.ParallelSignature";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_oneflow_2fcore_2fjob_2fparallel_5fsignature_2eproto);
    return ::descriptor_table_oneflow_2fcore_2fjob_2fparallel_5fsignature_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kBnInOp2ParallelDescSymbolIdFieldNumber = 2,
    kOpParallelDescSymbolIdFieldNumber = 1,
  };
  // map<string, int64> bn_in_op2parallel_desc_symbol_id = 2;
  int bn_in_op2parallel_desc_symbol_id_size() const;
  void clear_bn_in_op2parallel_desc_symbol_id();
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int64 >&
      bn_in_op2parallel_desc_symbol_id() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int64 >*
      mutable_bn_in_op2parallel_desc_symbol_id();

  // optional int64 op_parallel_desc_symbol_id = 1;
  bool has_op_parallel_desc_symbol_id() const;
  void clear_op_parallel_desc_symbol_id();
  ::PROTOBUF_NAMESPACE_ID::int64 op_parallel_desc_symbol_id() const;
  void set_op_parallel_desc_symbol_id(::PROTOBUF_NAMESPACE_ID::int64 value);

  // @@protoc_insertion_point(class_scope:oneflow.ParallelSignature)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      ParallelSignature_BnInOp2parallelDescSymbolIdEntry_DoNotUse,
      std::string, ::PROTOBUF_NAMESPACE_ID::int64,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64,
      0 > bn_in_op2parallel_desc_symbol_id_;
  ::PROTOBUF_NAMESPACE_ID::int64 op_parallel_desc_symbol_id_;
  friend struct ::TableStruct_oneflow_2fcore_2fjob_2fparallel_5fsignature_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ParallelSignature

// optional int64 op_parallel_desc_symbol_id = 1;
inline bool ParallelSignature::has_op_parallel_desc_symbol_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ParallelSignature::clear_op_parallel_desc_symbol_id() {
  op_parallel_desc_symbol_id_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ParallelSignature::op_parallel_desc_symbol_id() const {
  // @@protoc_insertion_point(field_get:oneflow.ParallelSignature.op_parallel_desc_symbol_id)
  return op_parallel_desc_symbol_id_;
}
inline void ParallelSignature::set_op_parallel_desc_symbol_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000001u;
  op_parallel_desc_symbol_id_ = value;
  // @@protoc_insertion_point(field_set:oneflow.ParallelSignature.op_parallel_desc_symbol_id)
}

// map<string, int64> bn_in_op2parallel_desc_symbol_id = 2;
inline int ParallelSignature::bn_in_op2parallel_desc_symbol_id_size() const {
  return bn_in_op2parallel_desc_symbol_id_.size();
}
inline void ParallelSignature::clear_bn_in_op2parallel_desc_symbol_id() {
  bn_in_op2parallel_desc_symbol_id_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int64 >&
ParallelSignature::bn_in_op2parallel_desc_symbol_id() const {
  // @@protoc_insertion_point(field_map:oneflow.ParallelSignature.bn_in_op2parallel_desc_symbol_id)
  return bn_in_op2parallel_desc_symbol_id_.GetMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int64 >*
ParallelSignature::mutable_bn_in_op2parallel_desc_symbol_id() {
  // @@protoc_insertion_point(field_mutable_map:oneflow.ParallelSignature.bn_in_op2parallel_desc_symbol_id)
  return bn_in_op2parallel_desc_symbol_id_.MutableMap();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace oneflow

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_oneflow_2fcore_2fjob_2fparallel_5fsignature_2eproto
