# Generated by Django 4.0.7 on 2022-08-23 10:28

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fleetfinder", "0002_alter_fleet_motd"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FleetInformation",
        ),
    ]
