# Generated by Django 3.2 on 2022-09-09 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_system', '0002_auto_20220908_1631'),
    ]

    operations = [
        migrations.RunSQL(
        'ALTER TABLE bs_hospital ALTER COLUMN is_active SET DEFAULT True;'
        )
    ]
