# Generated by Django 3.2 on 2022-09-20 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_system', '0017_doctor_is_online_consult'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_system.doctor', verbose_name='绑定医生'),
        ),
    ]
