# Generated by Django 3.2 on 2022-10-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_system', '0028_examinationdictionaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationdictionaries',
            name='distinguish',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='区分字段'),
        ),
        migrations.AddField(
            model_name='inspectiondictionaries',
            name='distinguish',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='区分字段'),
        ),
    ]
