# Generated by Django 3.2 on 2022-11-14 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_system', '0035_pharmacymanagement_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyEnterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='编码')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '药企管理',
                'verbose_name_plural': '药企管理',
                'db_table': 'bs_pharmacy_enterprise',
            },
        ),
        migrations.RemoveField(
            model_name='pharmacymanagement',
            name='belong_unit',
        ),
        migrations.AlterField(
            model_name='pharmacymanagement',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_system.hospital', verbose_name='所属医院'),
        ),
        migrations.AddField(
            model_name='pharmacymanagement',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_system.pharmacyenterprise', verbose_name='所属药企'),
        ),
    ]
