# Generated by Django 3.2 on 2022-11-14 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_system', '0036_auto_20221114_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('drug_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='药品编码')),
                ('drug_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='药品名称')),
                ('standards', models.CharField(blank=True, max_length=64, null=True, verbose_name='规格')),
                ('units', models.CharField(blank=True, max_length=64, null=True, verbose_name='单位')),
                ('origin_place', models.CharField(blank=True, max_length=64, null=True, verbose_name='产地')),
                ('manufacturer', models.CharField(blank=True, max_length=64, null=True, verbose_name='生产厂家')),
                ('valid_date', models.DateTimeField(auto_now=True, null=True, verbose_name='有效日期')),
                ('inventory_quantity', models.IntegerField(default=0, null=True, verbose_name='库存数量')),
                ('measurement_unit', models.CharField(blank=True, max_length=64, null=True, verbose_name='计量单位')),
                ('cost_unit_price', models.FloatField(null=True, verbose_name='成本单价')),
                ('cost_amount', models.FloatField(null=True, verbose_name='成本金额')),
                ('retail_unit_price', models.FloatField(null=True, verbose_name='零售单价')),
                ('retail_amount', models.FloatField(null=True, verbose_name='零售金额')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base_system.drugcategory', verbose_name='类别')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_system.hospital', verbose_name='所属医院')),
                ('pharmacy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_system.pharmacymanagement', verbose_name='所属药房')),
                ('preparation_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base_system.drugpreparationtype', verbose_name='制剂类型')),
            ],
            options={
                'verbose_name': '药房-药品',
                'verbose_name_plural': '药房-药品',
                'db_table': 'bs_pharmacy_drug',
            },
        ),
    ]
