# Generated by Django 3.2 on 2022-11-15 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_system', '0038_drugtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugdirectory',
            name='drug_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='base_system.drugtype', verbose_name='药品类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacydrug',
            name='drug_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='base_system.drugtype', verbose_name='药品类型'),
            preserve_default=False,
        ),
    ]
