# Generated by Django 3.2 on 2022-12-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_system', '0043_alter_hospital_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hos_images',
            field=models.CharField(default='hospital_images', max_length=100, verbose_name='医院图片'),
        ),
    ]
