# Generated by Django 3.2 on 2022-12-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_system', '0044_alter_hospital_hos_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.CharField(default='doctor_photo', max_length=100, verbose_name='医生照片'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(default='user_avatar', max_length=100, verbose_name='用户头像'),
        ),
    ]
