
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-09T15:53:24+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6d594a1c612ef51bd7c69666d4cf6a30dc934df0",
 "version": "0.1.65"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
