# Generated by Django 3.1.12 on 2022-03-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otp", "0003_auto_20220117_0617"),
    ]

    operations = [
        migrations.AddField(
            model_name="onetruepairing",
            name="meta",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
