
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-05T12:47:08+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "95008d1fc9e453374b2e5a3d7609295c79856b59",
 "version": "v1.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
