# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oneflow/core/memory/memory_block.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oneflow.core.memory import memory_case_pb2 as oneflow_dot_core_dot_memory_dot_memory__case__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='oneflow/core/memory/memory_block.proto',
  package='oneflow',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n&oneflow/core/memory/memory_block.proto\x12\x07oneflow\x1a%oneflow/core/memory/memory_case.proto\"\xa6\x02\n\rMemBlockProto\x12\x14\n\x0cmem_block_id\x18\x01 \x02(\x03\x12\x0e\n\x06job_id\x18\x02 \x03(\x03\x12\x12\n\nmachine_id\x18\x03 \x02(\x03\x12%\n\x08mem_case\x18\x04 \x02(\x0b\x32\x13.oneflow.MemoryCase\x12\x18\n\x10\x65nable_reuse_mem\x18\x05 \x02(\x08\x12\x14\n\x08\x63hunk_id\x18\x06 \x01(\x03:\x02-1\x12\x18\n\x0c\x63hunk_offset\x18\x07 \x01(\x03:\x02-1\x12\x10\n\x08mem_size\x18\x08 \x02(\x03\x12\x18\n\x0cthrd_id_hint\x18\t \x01(\x03:\x02-1\x12\x1a\n\x10variable_op_name\x18\n \x01(\t:\x00\x12\"\n\x13is_separated_header\x18\x0b \x01(\x08:\x05\x66\x61lse\"{\n\nChunkProto\x12\x10\n\x08\x63hunk_id\x18\x01 \x02(\x03\x12\x0e\n\x06job_id\x18\x02 \x03(\x03\x12\x12\n\nmachine_id\x18\x03 \x02(\x03\x12%\n\x08mem_case\x18\x04 \x02(\x0b\x32\x13.oneflow.MemoryCase\x12\x10\n\x08mem_size\x18\x05 \x02(\x03\"e\n\x14MemBlockAndChunkList\x12)\n\tmem_block\x18\x01 \x03(\x0b\x32\x16.oneflow.MemBlockProto\x12\"\n\x05\x63hunk\x18\x02 \x03(\x0b\x32\x13.oneflow.ChunkProto')
  ,
  dependencies=[oneflow_dot_core_dot_memory_dot_memory__case__pb2.DESCRIPTOR,])




_MEMBLOCKPROTO = _descriptor.Descriptor(
  name='MemBlockProto',
  full_name='oneflow.MemBlockProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mem_block_id', full_name='oneflow.MemBlockProto.mem_block_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='job_id', full_name='oneflow.MemBlockProto.job_id', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='machine_id', full_name='oneflow.MemBlockProto.machine_id', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mem_case', full_name='oneflow.MemBlockProto.mem_case', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enable_reuse_mem', full_name='oneflow.MemBlockProto.enable_reuse_mem', index=4,
      number=5, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chunk_id', full_name='oneflow.MemBlockProto.chunk_id', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chunk_offset', full_name='oneflow.MemBlockProto.chunk_offset', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mem_size', full_name='oneflow.MemBlockProto.mem_size', index=7,
      number=8, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thrd_id_hint', full_name='oneflow.MemBlockProto.thrd_id_hint', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='variable_op_name', full_name='oneflow.MemBlockProto.variable_op_name', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_separated_header', full_name='oneflow.MemBlockProto.is_separated_header', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=385,
)


_CHUNKPROTO = _descriptor.Descriptor(
  name='ChunkProto',
  full_name='oneflow.ChunkProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chunk_id', full_name='oneflow.ChunkProto.chunk_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='job_id', full_name='oneflow.ChunkProto.job_id', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='machine_id', full_name='oneflow.ChunkProto.machine_id', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mem_case', full_name='oneflow.ChunkProto.mem_case', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mem_size', full_name='oneflow.ChunkProto.mem_size', index=4,
      number=5, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=510,
)


_MEMBLOCKANDCHUNKLIST = _descriptor.Descriptor(
  name='MemBlockAndChunkList',
  full_name='oneflow.MemBlockAndChunkList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mem_block', full_name='oneflow.MemBlockAndChunkList.mem_block', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chunk', full_name='oneflow.MemBlockAndChunkList.chunk', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=512,
  serialized_end=613,
)

_MEMBLOCKPROTO.fields_by_name['mem_case'].message_type = oneflow_dot_core_dot_memory_dot_memory__case__pb2._MEMORYCASE
_CHUNKPROTO.fields_by_name['mem_case'].message_type = oneflow_dot_core_dot_memory_dot_memory__case__pb2._MEMORYCASE
_MEMBLOCKANDCHUNKLIST.fields_by_name['mem_block'].message_type = _MEMBLOCKPROTO
_MEMBLOCKANDCHUNKLIST.fields_by_name['chunk'].message_type = _CHUNKPROTO
DESCRIPTOR.message_types_by_name['MemBlockProto'] = _MEMBLOCKPROTO
DESCRIPTOR.message_types_by_name['ChunkProto'] = _CHUNKPROTO
DESCRIPTOR.message_types_by_name['MemBlockAndChunkList'] = _MEMBLOCKANDCHUNKLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MemBlockProto = _reflection.GeneratedProtocolMessageType('MemBlockProto', (_message.Message,), {
  'DESCRIPTOR' : _MEMBLOCKPROTO,
  '__module__' : 'oneflow.core.memory.memory_block_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.MemBlockProto)
  })
_sym_db.RegisterMessage(MemBlockProto)

ChunkProto = _reflection.GeneratedProtocolMessageType('ChunkProto', (_message.Message,), {
  'DESCRIPTOR' : _CHUNKPROTO,
  '__module__' : 'oneflow.core.memory.memory_block_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.ChunkProto)
  })
_sym_db.RegisterMessage(ChunkProto)

MemBlockAndChunkList = _reflection.GeneratedProtocolMessageType('MemBlockAndChunkList', (_message.Message,), {
  'DESCRIPTOR' : _MEMBLOCKANDCHUNKLIST,
  '__module__' : 'oneflow.core.memory.memory_block_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.MemBlockAndChunkList)
  })
_sym_db.RegisterMessage(MemBlockAndChunkList)


# @@protoc_insertion_point(module_scope)
