
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-05T11:43:36-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "17d4be79c84b8a0adcfd26e1d795e74318daf5c0",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
