
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-04T16:33:06-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "0fe7289716b9971eab5e185c59b02d0dd4f437b2",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
