
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-03T14:29:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4d6c1fbd2ecc411c8c33192ef6664dd42fcacccb",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
