class Data:
    SYNC = b"S"
    SYNC_LENGTH = 1
    REQUEST_LENGHT = 4
    BUFFER_SIZE = 8192
    CLOSE_CONNECTION = "CCON"
    SEND_AUTHENTICATION = "SAUT"
    RECV_AUTHENTICATION = "RAUT"
    SEND_FILE = "SFIL"
    RECEIVE_FILE = "RFIL"
