# -*- coding: utf-8 -*-
from setuptools import setup

package_dir = \
{'': 'src'}

packages = \
['terrascript',
 'terrascript.aws',
 'terrascript.aws.accessanalyzer',
 'terrascript.aws.account',
 'terrascript.aws.acm',
 'terrascript.aws.acmpca',
 'terrascript.aws.amp',
 'terrascript.aws.amplify',
 'terrascript.aws.api_gateway',
 'terrascript.aws.apigatewayv2',
 'terrascript.aws.appconfig',
 'terrascript.aws.appflow',
 'terrascript.aws.appintegrations',
 'terrascript.aws.application_auto_scaling',
 'terrascript.aws.applicationinsights',
 'terrascript.aws.appmesh',
 'terrascript.aws.apprunner',
 'terrascript.aws.appstream',
 'terrascript.aws.appsync',
 'terrascript.aws.athena',
 'terrascript.aws.auto_scaling',
 'terrascript.aws.autoscaling',
 'terrascript.aws.autoscalingplans',
 'terrascript.aws.backup',
 'terrascript.aws.batch',
 'terrascript.aws.budgets',
 'terrascript.aws.ce',
 'terrascript.aws.chime',
 'terrascript.aws.cloud9',
 'terrascript.aws.cloud_map',
 'terrascript.aws.cloudcontrolapi',
 'terrascript.aws.cloudformation',
 'terrascript.aws.cloudfront',
 'terrascript.aws.cloudhsm',
 'terrascript.aws.cloudsearch',
 'terrascript.aws.cloudtrail',
 'terrascript.aws.cloudwatch',
 'terrascript.aws.codeartifact',
 'terrascript.aws.codebuild',
 'terrascript.aws.codecommit',
 'terrascript.aws.codedeploy',
 'terrascript.aws.codepipeline',
 'terrascript.aws.codestarconnections',
 'terrascript.aws.codestarnotifications',
 'terrascript.aws.cognito',
 'terrascript.aws.cognito_identity',
 'terrascript.aws.comprehend',
 'terrascript.aws.config',
 'terrascript.aws.connect',
 'terrascript.aws.cost_and_usage_report',
 'terrascript.aws.dataexchange',
 'terrascript.aws.datapipeline',
 'terrascript.aws.datasync',
 'terrascript.aws.detective',
 'terrascript.aws.devicefarm',
 'terrascript.aws.direct_connect',
 'terrascript.aws.dlm',
 'terrascript.aws.dms',
 'terrascript.aws.docdb',
 'terrascript.aws.ds',
 'terrascript.aws.dynamodb',
 'terrascript.aws.dynamodb_accelerator',
 'terrascript.aws.ebs',
 'terrascript.aws.ec2',
 'terrascript.aws.ecr',
 'terrascript.aws.ecrpublic',
 'terrascript.aws.ecs',
 'terrascript.aws.efs',
 'terrascript.aws.eks',
 'terrascript.aws.elastic_beanstalk',
 'terrascript.aws.elasticache',
 'terrascript.aws.elasticsearch',
 'terrascript.aws.elastictranscoder',
 'terrascript.aws.elb',
 'terrascript.aws.elb_classic',
 'terrascript.aws.elemental_mediaconvert',
 'terrascript.aws.elemental_mediapackage',
 'terrascript.aws.elemental_mediastore',
 'terrascript.aws.emr',
 'terrascript.aws.emrcontainers',
 'terrascript.aws.emrserverless',
 'terrascript.aws.eventbridge',
 'terrascript.aws.fis',
 'terrascript.aws.fms',
 'terrascript.aws.fsx',
 'terrascript.aws.gamelift',
 'terrascript.aws.glacier',
 'terrascript.aws.globalaccelerator',
 'terrascript.aws.glue',
 'terrascript.aws.grafana',
 'terrascript.aws.guardduty',
 'terrascript.aws.iam',
 'terrascript.aws.identitystore',
 'terrascript.aws.imagebuilder',
 'terrascript.aws.inspector',
 'terrascript.aws.iot',
 'terrascript.aws.kendra',
 'terrascript.aws.keyspaces',
 'terrascript.aws.kinesis',
 'terrascript.aws.kinesis_analytics',
 'terrascript.aws.kinesis_firehose',
 'terrascript.aws.kinesis_video',
 'terrascript.aws.kinesisanalyticsv2',
 'terrascript.aws.kms',
 'terrascript.aws.lakeformation',
 'terrascript.aws.lambda_',
 'terrascript.aws.lex',
 'terrascript.aws.licensemanager',
 'terrascript.aws.lightsail',
 'terrascript.aws.location',
 'terrascript.aws.macie',
 'terrascript.aws.macie2',
 'terrascript.aws.managed_streaming_for_kafka',
 'terrascript.aws.managed_streaming_for_kafka_connect',
 'terrascript.aws.memorydb',
 'terrascript.aws.meta_data_sources',
 'terrascript.aws.mq',
 'terrascript.aws.mwaa',
 'terrascript.aws.neptune',
 'terrascript.aws.networkfirewall',
 'terrascript.aws.networkmanager',
 'terrascript.aws.opensearch',
 'terrascript.aws.opsworks',
 'terrascript.aws.organizations',
 'terrascript.aws.outposts',
 'terrascript.aws.pinpoint',
 'terrascript.aws.pricing',
 'terrascript.aws.qldb',
 'terrascript.aws.quicksight',
 'terrascript.aws.ram',
 'terrascript.aws.rds',
 'terrascript.aws.redshift',
 'terrascript.aws.redshiftdata',
 'terrascript.aws.redshiftserverless',
 'terrascript.aws.resourcegroups',
 'terrascript.aws.resourcegroupstagging',
 'terrascript.aws.rolesanywhere',
 'terrascript.aws.route53',
 'terrascript.aws.route53_resolver',
 'terrascript.aws.route53domains',
 'terrascript.aws.route53recoverycontrolconfig',
 'terrascript.aws.route53recoveryreadiness',
 'terrascript.aws.rum',
 'terrascript.aws.s3',
 'terrascript.aws.s3control',
 'terrascript.aws.s3outposts',
 'terrascript.aws.sagemaker',
 'terrascript.aws.schemas',
 'terrascript.aws.sdb',
 'terrascript.aws.secretsmanager',
 'terrascript.aws.securityhub',
 'terrascript.aws.serverlessapplicationrepository',
 'terrascript.aws.servicecatalog',
 'terrascript.aws.servicequotas',
 'terrascript.aws.ses',
 'terrascript.aws.sfn',
 'terrascript.aws.shield',
 'terrascript.aws.signer',
 'terrascript.aws.sns',
 'terrascript.aws.sqs',
 'terrascript.aws.ssm',
 'terrascript.aws.ssoadmin',
 'terrascript.aws.storagegateway',
 'terrascript.aws.sts',
 'terrascript.aws.swf',
 'terrascript.aws.synthetics',
 'terrascript.aws.timestreamwrite',
 'terrascript.aws.transcribe',
 'terrascript.aws.transfer',
 'terrascript.aws.transit_gateway',
 'terrascript.aws.vpc',
 'terrascript.aws.vpc_ipam',
 'terrascript.aws.vpn',
 'terrascript.aws.waf',
 'terrascript.aws.wafregional',
 'terrascript.aws.wavelength',
 'terrascript.aws.worklink',
 'terrascript.aws.workspaces',
 'terrascript.aws.x_ray']

package_data = \
{'': ['*']}

install_requires = \
['terrascript-core>=1.0.4,<2.0.0']

setup_kwargs = {
    'name': 'terrascript-aws',
    'version': '1.0.1',
    'description': '',
    'long_description': None,
    'author': 'csylaios',
    'author_email': 'chris.sylaios@gmail.com',
    'maintainer': None,
    'maintainer_email': None,
    'url': None,
    'package_dir': package_dir,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.9,<3.11',
}


setup(**setup_kwargs)
