# Generated by Django 4.0.3 on 2022-03-31 06:05

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_game_english_patched_game_english_patched_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="region",
            field=models.CharField(
                choices=[
                    ("US", "USA"),
                    ("EU", "Europe"),
                    ("JP", "Japan"),
                    ("X", "Unknown"),
                ],
                default=games.models.Game.Region["X"],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="undub",
            field=models.BooleanField(default=False),
        ),
    ]
