
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-05T04:21:52+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d095001c318eab0597862578e61d76faf564e9d1",
 "version": "1.17.1.post0.dev972"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
