# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oneflow/core/register/register_desc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oneflow.core.register import blob_desc_pb2 as oneflow_dot_core_dot_register_dot_blob__desc__pb2
from oneflow.core.register import logical_blob_id_pb2 as oneflow_dot_core_dot_register_dot_logical__blob__id__pb2
from oneflow.core.memory import memory_case_pb2 as oneflow_dot_core_dot_memory_dot_memory__case__pb2
from oneflow.core.common import shape_pb2 as oneflow_dot_core_dot_common_dot_shape__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='oneflow/core/register/register_desc.proto',
  package='oneflow',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n)oneflow/core/register/register_desc.proto\x12\x07oneflow\x1a%oneflow/core/register/blob_desc.proto\x1a+oneflow/core/register/logical_blob_id.proto\x1a%oneflow/core/memory/memory_case.proto\x1a\x1foneflow/core/common/shape.proto\"a\n\x0fLbiBlobDescPair\x12#\n\x03lbi\x18\x01 \x02(\x0b\x32\x16.oneflow.LogicalBlobId\x12)\n\tblob_desc\x18\x02 \x02(\x0b\x32\x16.oneflow.BlobDescProto\"i\n\rDataRegstDesc\x12/\n\rlbi2blob_desc\x18\x01 \x03(\x0b\x32\x18.oneflow.LbiBlobDescPair\x12\'\n\ntime_shape\x18\x03 \x02(\x0b\x32\x13.oneflow.ShapeProto\"\x0f\n\rCtrlRegstDesc\"\x82\x01\n\x12RegstDescTypeProto\x12\x31\n\x0f\x64\x61ta_regst_desc\x18\x01 \x01(\x0b\x32\x16.oneflow.DataRegstDescH\x00\x12\x31\n\x0f\x63trl_regst_desc\x18\x03 \x01(\x0b\x32\x16.oneflow.CtrlRegstDescH\x00\x42\x06\n\x04type\"\xa2\x05\n\x0eRegstDescProto\x12\x15\n\rregst_desc_id\x18\x01 \x02(\x03\x12\x18\n\x10producer_task_id\x18\x02 \x02(\x03\x12\x18\n\x10\x63onsumer_task_id\x18\x03 \x03(\x03\x12\x18\n\x10min_register_num\x18\x04 \x02(\x05\x12\x18\n\x10max_register_num\x18\x05 \x02(\x05\x12\x14\n\x0cregister_num\x18\x06 \x02(\x05\x12%\n\x08mem_case\x18\x07 \x02(\x0b\x32\x13.oneflow.MemoryCase\x12\x34\n\x0fregst_desc_type\x18\x08 \x02(\x0b\x32\x1b.oneflow.RegstDescTypeProto\x12\x18\n\x10\x65nable_reuse_mem\x18\t \x02(\x08\x12\x14\n\x0cmem_block_id\x18\n \x02(\x03\x12\x18\n\x10mem_block_offset\x18\x0b \x02(\x03\x12)\n\x1dseparated_header_mem_block_id\x18\x0c \x01(\x03:\x02-1\x12*\n\x1einplace_consumed_regst_desc_id\x18\r \x01(\x03:\x02-1\x12\x31\n#hint_inplace_consumed_regst_desc_id\x18\x0e \x01(\x03:\x02-1H\x00\x12\x32\n$force_inplace_consumed_regst_desc_id\x18\x0f \x01(\x03:\x02-1H\x00\x12\x1a\n\x10variable_op_name\x18\x10 \x01(\t:\x00\x12\'\n\x1bmem_block_total_actor_count\x18\x14 \x01(\x03:\x02-1\x12\x1e\n\x12\x61lloc_before_actor\x18\x15 \x01(\x03:\x02-1\x12\x1c\n\x10\x66ree_after_actor\x18\x16 \x01(\x03:\x02-1B\x13\n\x11inplace_info_type')
  ,
  dependencies=[oneflow_dot_core_dot_register_dot_blob__desc__pb2.DESCRIPTOR,oneflow_dot_core_dot_register_dot_logical__blob__id__pb2.DESCRIPTOR,oneflow_dot_core_dot_memory_dot_memory__case__pb2.DESCRIPTOR,oneflow_dot_core_dot_common_dot_shape__pb2.DESCRIPTOR,])




_LBIBLOBDESCPAIR = _descriptor.Descriptor(
  name='LbiBlobDescPair',
  full_name='oneflow.LbiBlobDescPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lbi', full_name='oneflow.LbiBlobDescPair.lbi', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blob_desc', full_name='oneflow.LbiBlobDescPair.blob_desc', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=307,
)


_DATAREGSTDESC = _descriptor.Descriptor(
  name='DataRegstDesc',
  full_name='oneflow.DataRegstDesc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lbi2blob_desc', full_name='oneflow.DataRegstDesc.lbi2blob_desc', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_shape', full_name='oneflow.DataRegstDesc.time_shape', index=1,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=414,
)


_CTRLREGSTDESC = _descriptor.Descriptor(
  name='CtrlRegstDesc',
  full_name='oneflow.CtrlRegstDesc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=416,
  serialized_end=431,
)


_REGSTDESCTYPEPROTO = _descriptor.Descriptor(
  name='RegstDescTypeProto',
  full_name='oneflow.RegstDescTypeProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_regst_desc', full_name='oneflow.RegstDescTypeProto.data_regst_desc', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ctrl_regst_desc', full_name='oneflow.RegstDescTypeProto.ctrl_regst_desc', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='oneflow.RegstDescTypeProto.type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=434,
  serialized_end=564,
)


_REGSTDESCPROTO = _descriptor.Descriptor(
  name='RegstDescProto',
  full_name='oneflow.RegstDescProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='regst_desc_id', full_name='oneflow.RegstDescProto.regst_desc_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='producer_task_id', full_name='oneflow.RegstDescProto.producer_task_id', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='consumer_task_id', full_name='oneflow.RegstDescProto.consumer_task_id', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_register_num', full_name='oneflow.RegstDescProto.min_register_num', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_register_num', full_name='oneflow.RegstDescProto.max_register_num', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='register_num', full_name='oneflow.RegstDescProto.register_num', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mem_case', full_name='oneflow.RegstDescProto.mem_case', index=6,
      number=7, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='regst_desc_type', full_name='oneflow.RegstDescProto.regst_desc_type', index=7,
      number=8, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enable_reuse_mem', full_name='oneflow.RegstDescProto.enable_reuse_mem', index=8,
      number=9, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mem_block_id', full_name='oneflow.RegstDescProto.mem_block_id', index=9,
      number=10, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mem_block_offset', full_name='oneflow.RegstDescProto.mem_block_offset', index=10,
      number=11, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='separated_header_mem_block_id', full_name='oneflow.RegstDescProto.separated_header_mem_block_id', index=11,
      number=12, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inplace_consumed_regst_desc_id', full_name='oneflow.RegstDescProto.inplace_consumed_regst_desc_id', index=12,
      number=13, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hint_inplace_consumed_regst_desc_id', full_name='oneflow.RegstDescProto.hint_inplace_consumed_regst_desc_id', index=13,
      number=14, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='force_inplace_consumed_regst_desc_id', full_name='oneflow.RegstDescProto.force_inplace_consumed_regst_desc_id', index=14,
      number=15, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='variable_op_name', full_name='oneflow.RegstDescProto.variable_op_name', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mem_block_total_actor_count', full_name='oneflow.RegstDescProto.mem_block_total_actor_count', index=16,
      number=20, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alloc_before_actor', full_name='oneflow.RegstDescProto.alloc_before_actor', index=17,
      number=21, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='free_after_actor', full_name='oneflow.RegstDescProto.free_after_actor', index=18,
      number=22, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='inplace_info_type', full_name='oneflow.RegstDescProto.inplace_info_type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=567,
  serialized_end=1241,
)

_LBIBLOBDESCPAIR.fields_by_name['lbi'].message_type = oneflow_dot_core_dot_register_dot_logical__blob__id__pb2._LOGICALBLOBID
_LBIBLOBDESCPAIR.fields_by_name['blob_desc'].message_type = oneflow_dot_core_dot_register_dot_blob__desc__pb2._BLOBDESCPROTO
_DATAREGSTDESC.fields_by_name['lbi2blob_desc'].message_type = _LBIBLOBDESCPAIR
_DATAREGSTDESC.fields_by_name['time_shape'].message_type = oneflow_dot_core_dot_common_dot_shape__pb2._SHAPEPROTO
_REGSTDESCTYPEPROTO.fields_by_name['data_regst_desc'].message_type = _DATAREGSTDESC
_REGSTDESCTYPEPROTO.fields_by_name['ctrl_regst_desc'].message_type = _CTRLREGSTDESC
_REGSTDESCTYPEPROTO.oneofs_by_name['type'].fields.append(
  _REGSTDESCTYPEPROTO.fields_by_name['data_regst_desc'])
_REGSTDESCTYPEPROTO.fields_by_name['data_regst_desc'].containing_oneof = _REGSTDESCTYPEPROTO.oneofs_by_name['type']
_REGSTDESCTYPEPROTO.oneofs_by_name['type'].fields.append(
  _REGSTDESCTYPEPROTO.fields_by_name['ctrl_regst_desc'])
_REGSTDESCTYPEPROTO.fields_by_name['ctrl_regst_desc'].containing_oneof = _REGSTDESCTYPEPROTO.oneofs_by_name['type']
_REGSTDESCPROTO.fields_by_name['mem_case'].message_type = oneflow_dot_core_dot_memory_dot_memory__case__pb2._MEMORYCASE
_REGSTDESCPROTO.fields_by_name['regst_desc_type'].message_type = _REGSTDESCTYPEPROTO
_REGSTDESCPROTO.oneofs_by_name['inplace_info_type'].fields.append(
  _REGSTDESCPROTO.fields_by_name['hint_inplace_consumed_regst_desc_id'])
_REGSTDESCPROTO.fields_by_name['hint_inplace_consumed_regst_desc_id'].containing_oneof = _REGSTDESCPROTO.oneofs_by_name['inplace_info_type']
_REGSTDESCPROTO.oneofs_by_name['inplace_info_type'].fields.append(
  _REGSTDESCPROTO.fields_by_name['force_inplace_consumed_regst_desc_id'])
_REGSTDESCPROTO.fields_by_name['force_inplace_consumed_regst_desc_id'].containing_oneof = _REGSTDESCPROTO.oneofs_by_name['inplace_info_type']
DESCRIPTOR.message_types_by_name['LbiBlobDescPair'] = _LBIBLOBDESCPAIR
DESCRIPTOR.message_types_by_name['DataRegstDesc'] = _DATAREGSTDESC
DESCRIPTOR.message_types_by_name['CtrlRegstDesc'] = _CTRLREGSTDESC
DESCRIPTOR.message_types_by_name['RegstDescTypeProto'] = _REGSTDESCTYPEPROTO
DESCRIPTOR.message_types_by_name['RegstDescProto'] = _REGSTDESCPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LbiBlobDescPair = _reflection.GeneratedProtocolMessageType('LbiBlobDescPair', (_message.Message,), {
  'DESCRIPTOR' : _LBIBLOBDESCPAIR,
  '__module__' : 'oneflow.core.register.register_desc_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.LbiBlobDescPair)
  })
_sym_db.RegisterMessage(LbiBlobDescPair)

DataRegstDesc = _reflection.GeneratedProtocolMessageType('DataRegstDesc', (_message.Message,), {
  'DESCRIPTOR' : _DATAREGSTDESC,
  '__module__' : 'oneflow.core.register.register_desc_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.DataRegstDesc)
  })
_sym_db.RegisterMessage(DataRegstDesc)

CtrlRegstDesc = _reflection.GeneratedProtocolMessageType('CtrlRegstDesc', (_message.Message,), {
  'DESCRIPTOR' : _CTRLREGSTDESC,
  '__module__' : 'oneflow.core.register.register_desc_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.CtrlRegstDesc)
  })
_sym_db.RegisterMessage(CtrlRegstDesc)

RegstDescTypeProto = _reflection.GeneratedProtocolMessageType('RegstDescTypeProto', (_message.Message,), {
  'DESCRIPTOR' : _REGSTDESCTYPEPROTO,
  '__module__' : 'oneflow.core.register.register_desc_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.RegstDescTypeProto)
  })
_sym_db.RegisterMessage(RegstDescTypeProto)

RegstDescProto = _reflection.GeneratedProtocolMessageType('RegstDescProto', (_message.Message,), {
  'DESCRIPTOR' : _REGSTDESCPROTO,
  '__module__' : 'oneflow.core.register.register_desc_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.RegstDescProto)
  })
_sym_db.RegisterMessage(RegstDescProto)


# @@protoc_insertion_point(module_scope)
