# Generated by Django 4.0.4 on 2022-06-20 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergameprogress',
            name='finished_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergameprogress',
            name='started_ts',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
