"""
    node-server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.223
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.domain import Domain
globals()['Domain'] = Domain
from openapi_client.model.y_meta_axis import YMetaAxis


class TestYMetaAxis(unittest.TestCase):
    """YMetaAxis unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testYMetaAxis(self):
        """Test YMetaAxis"""
        # FIXME: construct object with mandatory attributes with example values
        # model = YMetaAxis()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
