"""
    node-server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.223
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.visualization_data import VisualizationData
from openapi_client.model.viz_info_type import VizInfoType
globals()['VisualizationData'] = VisualizationData
globals()['VizInfoType'] = VizInfoType
from openapi_client.model.visualization_response import VisualizationResponse


class TestVisualizationResponse(unittest.TestCase):
    """VisualizationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVisualizationResponse(self):
        """Test VisualizationResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VisualizationResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
