"""
    node-server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.223
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.data_state_type import DataStateType
from openapi_client.model.scatter_filter import ScatterFilter
from openapi_client.model.scatter_insight_type import ScatterInsightType
globals()['DataStateType'] = DataStateType
globals()['ScatterFilter'] = ScatterFilter
globals()['ScatterInsightType'] = ScatterInsightType
from openapi_client.model.under_representation_insight import UnderRepresentationInsight


class TestUnderRepresentationInsight(unittest.TestCase):
    """UnderRepresentationInsight unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnderRepresentationInsight(self):
        """Test UnderRepresentationInsight"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UnderRepresentationInsight()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
