"""
    node-server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.223
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.bounding_box import BoundingBox
globals()['BoundingBox'] = BoundingBox
from openapi_client.model.b_box_image_viz import BBoxImageViz


class TestBBoxImageViz(unittest.TestCase):
    """BBoxImageViz unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBBoxImageViz(self):
        """Test BBoxImageViz"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BBoxImageViz()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
