"""
    node-server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.223
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.get_stored_resource_url_params import GetStoredResourceUrlParams


class TestGetStoredResourceUrlParams(unittest.TestCase):
    """GetStoredResourceUrlParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetStoredResourceUrlParams(self):
        """Test GetStoredResourceUrlParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetStoredResourceUrlParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
