"""
    node-server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.223
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_activate(self):
        """Test case for activate

        """
        pass

    def test_add_dashboard(self):
        """Test case for add_dashboard

        """
        pass

    def test_add_dataset(self):
        """Test case for add_dataset

        """
        pass

    def test_add_export_model_job(self):
        """Test case for add_export_model_job

        """
        pass

    def test_add_issue(self):
        """Test case for add_issue

        """
        pass

    def test_add_project(self):
        """Test case for add_project

        """
        pass

    def test_add_secret_manager(self):
        """Test case for add_secret_manager

        """
        pass

    def test_add_version(self):
        """Test case for add_version

        """
        pass

    def test_continue_train(self):
        """Test case for continue_train

        """
        pass

    def test_create_model_test(self):
        """Test case for create_model_test

        """
        pass

    def test_create_organization(self):
        """Test case for create_organization

        """
        pass

    def test_delete_dashboard(self):
        """Test case for delete_dashboard

        """
        pass

    def test_delete_issue(self):
        """Test case for delete_issue

        """
        pass

    def test_delete_model(self):
        """Test case for delete_model

        """
        pass

    def test_delete_model_test(self):
        """Test case for delete_model_test

        """
        pass

    def test_delete_organization(self):
        """Test case for delete_organization

        """
        pass

    def test_delete_project(self):
        """Test case for delete_project

        """
        pass

    def test_delete_user_by_id(self):
        """Test case for delete_user_by_id

        """
        pass

    def test_delete_version(self):
        """Test case for delete_version

        """
        pass

    def test_delete_visualizations(self):
        """Test case for delete_visualizations

        """
        pass

    def test_evaluate(self):
        """Test case for evaluate

        """
        pass

    def test_extend_trial(self):
        """Test case for extend_trial

        """
        pass

    def test_get_all_project_model_tests(self):
        """Test case for get_all_project_model_tests

        """
        pass

    def test_get_all_slim_user_data(self):
        """Test case for get_all_slim_user_data

        """
        pass

    def test_get_balanced_accuracy(self):
        """Test case for get_balanced_accuracy

        """
        pass

    def test_get_confusion_metric_names(self):
        """Test case for get_confusion_metric_names

        """
        pass

    def test_get_current_project_version(self):
        """Test case for get_current_project_version

        """
        pass

    def test_get_dashboard(self):
        """Test case for get_dashboard

        """
        pass

    def test_get_dashlet_fields(self):
        """Test case for get_dashlet_fields

        """
        pass

    def test_get_dataset_version(self):
        """Test case for get_dataset_version

        """
        pass

    def test_get_dataset_versions(self):
        """Test case for get_dataset_versions

        """
        pass

    def test_get_datasets(self):
        """Test case for get_datasets

        """
        pass

    def test_get_demos(self):
        """Test case for get_demos

        """
        pass

    def test_get_exported_model_jobs(self):
        """Test case for get_exported_model_jobs

        """
        pass

    def test_get_f1_score(self):
        """Test case for get_f1_score

        """
        pass

    def test_get_jobs(self):
        """Test case for get_jobs

        """
        pass

    def test_get_kibana_dashboards(self):
        """Test case for get_kibana_dashboards

        """
        pass

    def test_get_kibana_dashlet_fields(self):
        """Test case for get_kibana_dashlet_fields

        """
        pass

    def test_get_latest_dataset_version(self):
        """Test case for get_latest_dataset_version

        """
        pass

    def test_get_machine_types(self):
        """Test case for get_machine_types

        """
        pass

    def test_get_max_active_users(self):
        """Test case for get_max_active_users

        """
        pass

    def test_get_model_epoch_loss(self):
        """Test case for get_model_epoch_loss

        """
        pass

    def test_get_model_insights(self):
        """Test case for get_model_insights

        """
        pass

    def test_get_model_test_result(self):
        """Test case for get_model_test_result

        """
        pass

    def test_get_model_visualizations(self):
        """Test case for get_model_visualizations

        """
        pass

    def test_get_models_by_hash(self):
        """Test case for get_models_by_hash

        """
        pass

    def test_get_models_by_version_id(self):
        """Test case for get_models_by_version_id

        """
        pass

    def test_get_notifications(self):
        """Test case for get_notifications

        """
        pass

    def test_get_organization_jobs(self):
        """Test case for get_organization_jobs

        """
        pass

    def test_get_organization_slim_user_data(self):
        """Test case for get_organization_slim_user_data

        """
        pass

    def test_get_organizations(self):
        """Test case for get_organizations

        """
        pass

    def test_get_pr_curve(self):
        """Test case for get_pr_curve

        """
        pass

    def test_get_project_dashboards(self):
        """Test case for get_project_dashboards

        """
        pass

    def test_get_project_issues(self):
        """Test case for get_project_issues

        """
        pass

    def test_get_project_slim_versions(self):
        """Test case for get_project_slim_versions

        """
        pass

    def test_get_projects(self):
        """Test case for get_projects

        """
        pass

    def test_get_recent_organization_models(self):
        """Test case for get_recent_organization_models

        """
        pass

    def test_get_roc(self):
        """Test case for get_roc

        """
        pass

    def test_get_secret_manager_list(self):
        """Test case for get_secret_manager_list

        """
        pass

    def test_get_single_issue(self):
        """Test case for get_single_issue

        """
        pass

    def test_get_single_model_test(self):
        """Test case for get_single_model_test

        """
        pass

    def test_get_statistics(self):
        """Test case for get_statistics

        """
        pass

    def test_get_stored_exported_model_resource_url(self):
        """Test case for get_stored_exported_model_resource_url

        """
        pass

    def test_get_stored_resource_url(self):
        """Test case for get_stored_resource_url

        """
        pass

    def test_get_training_jobs(self):
        """Test case for get_training_jobs

        """
        pass

    def test_get_upload_signed_url(self):
        """Test case for get_upload_signed_url

        """
        pass

    def test_get_visualization(self):
        """Test case for get_visualization

        """
        pass

    def test_health_check(self):
        """Test case for health_check

        """
        pass

    def test_import_demo_project(self):
        """Test case for import_demo_project

        """
        pass

    def test_import_model(self):
        """Test case for import_model

        """
        pass

    def test_is_training_job_running(self):
        """Test case for is_training_job_running

        """
        pass

    def test_key_gen(self):
        """Test case for key_gen

        """
        pass

    def test_key_login(self):
        """Test case for key_login

        """
        pass

    def test_load_model(self):
        """Test case for load_model

        """
        pass

    def test_load_version(self):
        """Test case for load_version

        """
        pass

    def test_login(self):
        """Test case for login

        """
        pass

    def test_logout(self):
        """Test case for logout

        """
        pass

    def test_modify_dataset_version_note(self):
        """Test case for modify_dataset_version_note

        """
        pass

    def test_parse_dataset(self):
        """Test case for parse_dataset

        """
        pass

    def test_population_exploration(self):
        """Test case for population_exploration

        """
        pass

    def test_request_trial(self):
        """Test case for request_trial

        """
        pass

    def test_resend_activation_mail(self):
        """Test case for resend_activation_mail

        """
        pass

    def test_reset_password(self):
        """Test case for reset_password

        """
        pass

    def test_sample_analysis(self):
        """Test case for sample_analysis

        """
        pass

    def test_sample_selection(self):
        """Test case for sample_selection

        """
        pass

    def test_save_analyzer_layout(self):
        """Test case for save_analyzer_layout

        """
        pass

    def test_save_dataset_version(self):
        """Test case for save_dataset_version

        """
        pass

    def test_send_reset_password_mail(self):
        """Test case for send_reset_password_mail

        """
        pass

    def test_send_user_message(self):
        """Test case for send_user_message

        """
        pass

    def test_set_default_organization(self):
        """Test case for set_default_organization

        """
        pass

    def test_set_organization_machine_type(self):
        """Test case for set_organization_machine_type

        """
        pass

    def test_set_user_metadata(self):
        """Test case for set_user_metadata

        """
        pass

    def test_set_user_notifications_as_read(self):
        """Test case for set_user_notifications_as_read

        """
        pass

    def test_signup(self):
        """Test case for signup

        """
        pass

    def test_start_trial(self):
        """Test case for start_trial

        """
        pass

    def test_stop_job(self):
        """Test case for stop_job

        """
        pass

    def test_terminate_job(self):
        """Test case for terminate_job

        """
        pass

    def test_train_from_initial_weights(self):
        """Test case for train_from_initial_weights

        """
        pass

    def test_train_from_scratch(self):
        """Test case for train_from_scratch

        """
        pass

    def test_trash_dataset(self):
        """Test case for trash_dataset

        """
        pass

    def test_trash_project(self):
        """Test case for trash_project

        """
        pass

    def test_trash_secret_manager(self):
        """Test case for trash_secret_manager

        """
        pass

    def test_update_dashboard(self):
        """Test case for update_dashboard

        """
        pass

    def test_update_issue(self):
        """Test case for update_issue

        """
        pass

    def test_update_model_test(self):
        """Test case for update_model_test

        """
        pass

    def test_update_organization_public_name(self):
        """Test case for update_organization_public_name

        """
        pass

    def test_update_secret_manager(self):
        """Test case for update_secret_manager

        """
        pass

    def test_update_user_name(self):
        """Test case for update_user_name

        """
        pass

    def test_update_user_organization(self):
        """Test case for update_user_organization

        """
        pass

    def test_update_user_role(self):
        """Test case for update_user_role

        """
        pass

    def test_update_user_status(self):
        """Test case for update_user_status

        """
        pass

    def test_update_version(self):
        """Test case for update_version

        """
        pass

    def test_warmup(self):
        """Test case for warmup

        """
        pass

    def test_who_am_i(self):
        """Test case for who_am_i

        """
        pass


if __name__ == '__main__':
    unittest.main()
