"""
    node-server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.223
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.issue_action import IssueAction
from openapi_client.model.issue_action_type import IssueActionType
globals()['IssueAction'] = IssueAction
globals()['IssueActionType'] = IssueActionType
from openapi_client.model.issue_activity import IssueActivity


class TestIssueActivity(unittest.TestCase):
    """IssueActivity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIssueActivity(self):
        """Test IssueActivity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IssueActivity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
