"""
    node-server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.223
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.request_trial_metadata import RequestTrialMetadata


class TestRequestTrialMetadata(unittest.TestCase):
    """RequestTrialMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestTrialMetadata(self):
        """Test RequestTrialMetadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RequestTrialMetadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
