"""
    node-server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.223
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.job import Job
from openapi_client.model.model_save_data import ModelSaveData
from openapi_client.model.model_type import ModelType
from openapi_client.model.training_params import TrainingParams
globals()['Job'] = Job
globals()['ModelSaveData'] = ModelSaveData
globals()['ModelType'] = ModelType
globals()['TrainingParams'] = TrainingParams
from openapi_client.model.model_populated_job import ModelPopulatedJob


class TestModelPopulatedJob(unittest.TestCase):
    """ModelPopulatedJob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelPopulatedJob(self):
        """Test ModelPopulatedJob"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ModelPopulatedJob()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
