"""
    node-server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.223
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.horizontal_bar_viz import HorizontalBarViz
globals()['HorizontalBarViz'] = HorizontalBarViz
from openapi_client.model.horizontal_bar_scatter_label import HorizontalBarScatterLabel


class TestHorizontalBarScatterLabel(unittest.TestCase):
    """HorizontalBarScatterLabel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHorizontalBarScatterLabel(self):
        """Test HorizontalBarScatterLabel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HorizontalBarScatterLabel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
