"""
    node-server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.223
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.get_f1_score_params import GetF1ScoreParams


class TestGetF1ScoreParams(unittest.TestCase):
    """GetF1ScoreParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetF1ScoreParams(self):
        """Test GetF1ScoreParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetF1ScoreParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
