"""
    node-server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.223
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.export_model_type_enum import ExportModelTypeEnum
globals()['ExportModelTypeEnum'] = ExportModelTypeEnum
from openapi_client.model.add_export_model_job_params import AddExportModelJobParams


class TestAddExportModelJobParams(unittest.TestCase):
    """AddExportModelJobParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddExportModelJobParams(self):
        """Test AddExportModelJobParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddExportModelJobParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
