"""
    node-server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.223
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.terminate_job_params import TerminateJobParams


class TestTerminateJobParams(unittest.TestCase):
    """TerminateJobParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTerminateJobParams(self):
        """Test TerminateJobParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TerminateJobParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
