"""
    node-server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.223
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.data_state_type import DataStateType
from openapi_client.model.sample_identity import SampleIdentity
from openapi_client.model.scatter_label import ScatterLabel
globals()['DataStateType'] = DataStateType
globals()['SampleIdentity'] = SampleIdentity
globals()['ScatterLabel'] = ScatterLabel
from openapi_client.model.scatter_viz_data_state import ScatterVizDataState


class TestScatterVizDataState(unittest.TestCase):
    """ScatterVizDataState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScatterVizDataState(self):
        """Test ScatterVizDataState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ScatterVizDataState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
