"""
    node-server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.223
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.data_state_for_eval import DataStateForEval
from openapi_client.model.training_params import TrainingParams
globals()['DataStateForEval'] = DataStateForEval
globals()['TrainingParams'] = TrainingParams
from openapi_client.model.evaluate_params import EvaluateParams


class TestEvaluateParams(unittest.TestCase):
    """EvaluateParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEvaluateParams(self):
        """Test EvaluateParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EvaluateParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
