
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-04T16:30:03-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "a08a4faaa474c1ea4c768ddf6b915707b909c721",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
