
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-04T05:34:00+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d69e4b32ee9722ea7839d5e619b0b3ded32b4ad7",
 "version": "1.17.1.post0.dev951"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
